const fs=require('fs'),path=require('path');
let imgC=3500;
function img(){imgC++;return`https://images.unsplash.com/photo-160059654${imgC}-${imgC}ab${imgC}cd?w=800&h=600&fit=crop&auto=format`;}
function d(s,n,nv,p,c,desc,ld,tips,addr,lat,lng,h,f,bt,tags,ft,o){
return{id:s,slug:s,name:n,nameVi:nv,provinceSlug:p,category:c,description:desc,longDescription:ld,
images:[{src:img(),alt:n,caption:`${n} – cảnh đẹp`},{src:img(),alt:`${n} view`,caption:`Khung cảnh tại ${n}`}],
tips,address:addr,coordinates:{lat,lng},openingHours:h,entryFee:f,bestTimeToVisit:bt,tags,featured:ft,order:o};}

const dests=[
// THANH HOÁ (4)
d("thanh-nha-ho","Thành Nhà Hồ","Thành Nhà Hồ","thanh-hoa","lich-su","Di sản Thế giới UNESCO – thành đá độc đáo duy nhất tại Đông Nam Á.","Thành Nhà Hồ xây năm 1397 bằng đá phiến lớn, UNESCO công nhận 2011. Là thành đá duy nhất ở ĐNA, tường thành đá nguyên khối nặng hàng chục tấn. Kiến trúc quân sự độc đáo thể hiện quyền lực nhà Hồ. Các cổng thành bằng đá vòm cuốn nguyên khối ấn tượng.",["Tham quan cổng thành phía Nam đẹp nhất","Thuê hướng dẫn viên","Kết hợp thăm đền thờ Lê Lợi"],"Vĩnh Lộc, Thanh Hoá",20.0783,105.5867,"7:00–17:00","25.000đ","Quanh năm",["di-sản-unesco","thành-đá","lịch-sử","kiến-trúc"],false,1),
d("sam-son","Bãi biển Sầm Sơn","Sầm Sơn","thanh-hoa","thien-nhien","Khu nghỉ mát biển nổi tiếng nhất miền Bắc với bãi cát dài và hải sản tươi.","Sầm Sơn cách TP. Thanh Hoá 16km, là bãi biển nổi tiếng nhất miền Bắc. Bãi cát trải dài 6km, nước biển sạch. Khu resort, khách sạn dọc bờ biển. Hải sản tươi ngon: tôm, cua, ghẹ. Mùa hè đông du khách, đặc biệt người Hà Nội.",["Tránh cuối tuần mùa hè vì rất đông","Ăn hải sản chợ cá Sầm Sơn","Kết hợp thăm đền Độc Cước trên mỏm đá"],"TP. Sầm Sơn, Thanh Hoá",19.7533,105.9017,"Luôn mở cửa","Miễn phí","Tháng 5–8",["biển","nghỉ-mát","hải-sản","cát"],false,2),
d("vuon-quoc-gia-ben-en","VQG Bến En","Vườn Quốc gia Bến En","thanh-hoa","thien-nhien","Rừng nguyên sinh quanh hồ nước lớn với hệ sinh thái phong phú.","VQG Bến En rộng 16.634ha với hồ sông Mực trong xanh bao quanh bởi rừng nguyên sinh. Nhiều đảo nhỏ trên hồ xanh mướt. Hệ động thực vật phong phú: voọc, gấu, nhiều loài chim quý. Du khách đi thuyền trên hồ, trekking rừng, cắm trại.",["Đi thuyền trên hồ sông Mực","Cắm trại trên đảo","Mang thuốc chống muỗi"],"Như Thanh, Thanh Hoá",19.6033,105.5433,"7:00–17:00","40.000đ","Tháng 4–10",["rừng","hồ","sinh-thái","trekking"],false,3),
d("lam-kinh","Lam Kinh","Khu di tích Lam Kinh","thanh-hoa","lich-su","Nơi phát tích khởi nghĩa Lam Sơn của vua Lê Lợi, kinh đô thứ hai triều Lê.","Lam Kinh là quê hương Lê Lợi – nơi phát tích khởi nghĩa Lam Sơn đánh đuổi quân Minh. Thành điện Lam Kinh xây từ 1428, là kinh đô thứ hai triều Lê, nơi an nghỉ các vua Lê. Khu di tích rộng với lăng mộ, đền thờ giữa rừng lim cổ thụ. Cây đa 600 tuổi ấn tượng.",["Tham quan cùng hướng dẫn viên","Chiêm ngưỡng cây đa 600 tuổi","Kết hợp thăm Thành Nhà Hồ"],"Thọ Xuân, Thanh Hoá",19.8700,105.4900,"7:00–17:00","Miễn phí","Quanh năm",["di-tích","lê-lợi","lịch-sử","rừng-lim"],false,4),
// NGHỆ AN (4)
d("cua-lo","Bãi biển Cửa Lò","Cửa Lò","nghe-an","thien-nhien","Bãi biển nổi tiếng nhất xứ Nghệ với cát mịn và sóng vừa.","Cửa Lò cách TP. Vinh 16km, bãi biển dài 10km, cát mịn, sóng vừa phù hợp tắm biển. Khu resort và khách sạn ven biển phát triển. Hải sản Cửa Lò tươi ngon nổi tiếng. Gần đảo Ngư có nhiều hoạt động biển.",["Tắm biển buổi sáng sóng êm","Ăn hải sản chợ Cửa Lò","Đi thuyền ra đảo Ngư nếu có thời gian"],"TX. Cửa Lò, Nghệ An",18.7917,105.7233,"Luôn mở cửa","Miễn phí","Tháng 5–8",["biển","cát-mịn","hải-sản","nghỉ-mát"],false,1),
d("que-bac-kim-lien","Quê Bác Kim Liên","Khu di tích Kim Liên","nghe-an","lich-su","Quê hương Chủ tịch Hồ Chí Minh – nơi lưu giữ ngôi nhà Bác sinh ra.","Kim Liên (Nam Đàn) là quê nội của Bác Hồ. Khu di tích gồm nhà ở quê nội và quê ngoại (làng Hoàng Trù). Nhà tranh 5 gian giữ nguyên bản giản dị. Bảo tàng Kim Liên trưng bày hiện vật. Hàng năm dịp 19/5 có nhiều hoạt động kỷ niệm.",["Mặc trang phục lịch sự","Tham quan bảo tàng Kim Liên","Dịp 19/5 nhiều hoạt động"],"Kim Liên, Nam Đàn, Nghệ An",18.6717,105.4933,"7:30–17:00","Miễn phí","Quanh năm",["quê-bác","lịch-sử","di-tích","giáo-dục"],false,2),
d("vuon-quoc-gia-pu-mat","VQG Pù Mát","Vườn Quốc gia Pù Mát","nghe-an","thien-nhien","Khu dự trữ sinh quyển thế giới với rừng nguyên sinh lớn nhất miền Trung.","VQG Pù Mát rộng 94.275ha, Khu dự trữ Sinh quyển Thế giới UNESCO. Rừng nguyên sinh lớn nhất miền Trung với đa dạng sinh học cao. Nhiều loài quý: sao la, hổ, voi. Thác Khe Kèm cao 150m là điểm tham quan nổi bật.",["Thăm thác Khe Kèm","Thuê hướng dẫn viên bản địa","Mang đồ trekking phù hợp"],"Con Cuông, Nghệ An",19.0000,104.8000,"Luôn mở cửa","40.000đ","Tháng 3–10",["rừng","sinh-quyển","thác","trekking"],false,3),
d("thanh-co-vinh","Thành cổ Vinh","Thành cổ Nghệ An","nghe-an","lich-su","Di tích thành cổ thời Nguyễn, nay là công viên trung tâm TP. Vinh.","Thành cổ Vinh xây thời Gia Long (1804), kiến trúc Vauban. Nay chỉ còn cổng thành và một đoạn tường, được trùng tu thành công viên. Khu vực trung tâm TP. Vinh sầm uất, gần quảng trường và bảo tàng. Là nơi gắn liền với phong trào Xô Viết Nghệ Tĩnh.",["Dạo công viên thành cổ","Kết hợp thăm bảo tàng Nghệ An","Ăn cháo lươn xứ Nghệ gần đó"],"TP. Vinh, Nghệ An",18.6789,105.6817,"Luôn mở cửa","Miễn phí","Quanh năm",["thành-cổ","lịch-sử","công-viên"],false,4),
// HÀ TĨNH (3)
d("chua-huong-tich","Chùa Hương Tích","Chùa Hương Tích","ha-tinh","tam-linh","\"Hoan Châu đệ nhất danh lam\" trên núi Hồng Lĩnh linh thiêng.","Chùa Hương Tích nằm trên núi Hồng Lĩnh ở độ cao 650m, được mệnh danh \"Hoan Châu đệ nhất danh lam\". Chùa xây từ thời Trần, kiến trúc cổ kính giữa rừng thông. Đường lên chùa qua 599 bậc đá giữa rừng cây. Từ chùa ngắm toàn cảnh đồng bằng Hà Tĩnh.",["Leo 599 bậc đá, cần sức khoẻ","Mang nước và áo mưa","Có cáp treo lên gần chùa"],"Can Lộc, Hà Tĩnh",18.5000,105.7500,"6:00–18:00","Cáp treo: 80.000đ","Tháng 1–4",["chùa","núi","tâm-linh","trekking"],false,1),
d("bai-bien-thien-cam","Bãi biển Thiên Cầm","Thiên Cầm","ha-tinh","thien-nhien","Bãi biển đẹp nhất Hà Tĩnh với cát trắng dài và nước biển trong xanh.","Thiên Cầm là bãi biển đẹp nhất Hà Tĩnh, cát trắng mịn, nước trong. Hai mỏm đá hai đầu bãi tạo dáng đàn cầm. Khu nghỉ dưỡng phát triển ven biển. Hải sản tươi giá rẻ. Yên tĩnh hơn nhiều so với các bãi biển nổi tiếng khác.",["Bãi biển yên tĩnh, ít đông","Hải sản tươi giá rẻ","Kết hợp thăm chùa Hương Tích"],"Cẩm Xuyên, Hà Tĩnh",18.2467,105.9733,"Luôn mở cửa","Miễn phí","Tháng 5–8",["biển","cát-trắng","yên-tĩnh","hải-sản"],false,2),
d("vuon-quoc-gia-vu-quang","VQG Vũ Quang","Vườn Quốc gia Vũ Quang","ha-tinh","thien-nhien","Nơi phát hiện loài Sao La – \"kỳ lân châu Á\" quý hiếm.","VQG Vũ Quang nổi tiếng thế giới khi phát hiện loài Sao La (1992) – một trong những phát hiện động vật lớn nhất thế kỷ 20. Rừng nguyên sinh rộng lớn, đa dạng sinh học cao. Nhiều loài thú quý: mang lớn, voọc. Du khách trekking rừng khám phá hệ sinh thái.",["Thuê hướng dẫn viên bản địa","Mang đồ trekking đầy đủ","Cơ hội thấy Sao La rất hiếm"],"Vũ Quang, Hà Tĩnh",18.3500,105.3000,"Luôn mở cửa","30.000đ","Tháng 3–10",["rừng","sao-la","bảo-tồn","trekking"],false,3),
// QUẢNG BÌNH (4)
d("dong-phong-nha","Động Phong Nha","Động Phong Nha","quang-binh","thien-nhien","Hang động với sông ngầm dài nhất thế giới, Di sản Thiên nhiên Thế giới UNESCO.","Động Phong Nha thuộc VQG Phong Nha – Kẻ Bàng, UNESCO công nhận 2003. Hang có sông ngầm dài 13.969m – dài nhất thế giới. Du khách đi thuyền trên sông ngầm xuyên qua hang, ngắm nhũ đá lung linh. Ánh sáng chiếu xuyên nhũ đá tạo khung cảnh huyền ảo.",["Đi thuyền vào hang rất ấn tượng","Mặc áo khoác vì trong hang mát","Kết hợp thăm Động Thiên Đường"],"Sơn Trạch, Bố Trạch, Quảng Bình",17.5742,106.2828,"7:00–16:00","150.000đ (gồm thuyền)","Tháng 4–8",["hang-động","sông-ngầm","di-sản-unesco","thuyền"],true,1),
d("dong-thien-duong","Động Thiên Đường","Động Thiên Đường (Paradise Cave)","quang-binh","thien-nhien","Hang khô dài nhất châu Á với nhũ đá lộng lẫy như cung điện ngầm.","Động Thiên Đường dài 31,4km, rộng nhất 150m, cao nhất 72m – hang khô dài nhất châu Á. Nhũ đá và măng đá tạo thành cung điện ngầm lộng lẫy. Hệ thống cầu gỗ dài 1,1km cho du khách đi bộ ngắm. Ánh đèn chiếu sáng tạo hiệu ứng mê hoặc.",["Tour 1km (phổ biến) hoặc 7km (mạo hiểm)","Mang giày thoải mái","Mang áo ấm, trong hang 20°C"],"Sơn Trạch, Bố Trạch, Quảng Bình",17.5500,106.2167,"7:00–16:00","250.000đ","Quanh năm",["hang-động","nhũ-đá","kỷ-lục","thiên-nhiên"],false,2),
d("song-chay-hang-toi","Sông Chày – Hang Tối","Sông Chày – Hang Tối","quang-binh","giai-tri","Tour mạo hiểm kết hợp zip-line, chèo kayak và tắm bùn trong hang.","Tour Sông Chày – Hang Tối là trải nghiệm phổ biến nhất Quảng Bình. Bắt đầu bằng zip-line 400m vượt sông Chày. Sau đó chèo kayak trên sông. Cuối cùng là tắm bùn trong Hang Tối (Dark Cave) – hang động ngầm nước. Cảm giác mạo hiểm và vui nhộn.",["Mang đồ bơi và đồ thay","Không phù hợp trẻ dưới 1m","Zip-line rất thú vị"],"Sơn Trạch, Bố Trạch, Quảng Bình",17.5600,106.2500,"7:00–15:00","450.000đ (trọn gói)","Tháng 4–8",["mạo-hiểm","zip-line","kayak","hang-tối"],false,3),
d("bai-bien-nhat-le","Bãi biển Nhật Lệ","Bãi biển Nhật Lệ","quang-binh","thien-nhien","Bãi biển sạch đẹp của TP. Đồng Hới, cửa ngõ khám phá Phong Nha.","Bãi biển Nhật Lệ nằm tại cửa sông Nhật Lệ, TP. Đồng Hới. Cát trắng mịn, nước trong xanh. Cầu Nhật Lệ lung linh về đêm. Quanh bãi biển có nhiều nhà hàng hải sản. Là nơi nghỉ ngơi lý tưởng sau ngày khám phá hang động Phong Nha.",["Tắm biển buổi chiều mát mẻ","Dạo cầu Nhật Lệ ban đêm","Ăn bánh bột lọc Quảng Bình"],"Bờ sông Nhật Lệ, TP. Đồng Hới",17.4750,106.6117,"Luôn mở cửa","Miễn phí","Tháng 4–8",["biển","cầu","hải-sản","đồng-hới"],false,4),
// QUẢNG TRỊ (3)
d("thanh-co-quang-tri","Thành cổ Quảng Trị","Thành cổ Quảng Trị","quang-tri","lich-su","Biểu tượng hy sinh anh dũng của 81 ngày đêm mùa hè đỏ lửa 1972.","Thành cổ Quảng Trị là nơi diễn ra trận chiến 81 ngày đêm (1972) ác liệt nhất chiến tranh. Hàng ngàn chiến sĩ đã hy sinh giữ thành. Nay là đài tưởng niệm thiêng liêng. Bảo tàng trưng bày hiện vật chiến tranh. Mỗi đêm thả hoa đăng tưởng niệm trên sông Thạch Hãn.",["Thả hoa đăng tối trên sông Thạch Hãn","Tham quan bảo tàng bên trong","Đến dịp 27/7 để dự lễ tưởng niệm"],"TX. Quảng Trị, Quảng Trị",16.7333,107.1833,"7:00–17:00","Miễn phí","Quanh năm",["thành-cổ","lịch-sử","chiến-tranh","tưởng-niệm"],false,1),
d("dia-dao-vinh-moc","Địa đạo Vĩnh Mốc","Địa đạo Vĩnh Mốc","quang-tri","lich-su","Hệ thống đường hầm 3 tầng nơi cả làng sinh sống dưới lòng đất suốt chiến tranh.","Địa đạo Vĩnh Mốc dài 1.700m, sâu 12–23m, gồm 3 tầng với phòng ở, giếng nước, hội trường. Cả làng (17 gia đình) sống dưới lòng đất suốt 5 năm chiến tranh. 17 em bé ra đời trong địa đạo. Khác Củ Chi, Vĩnh Mốc rộng rãi hơn để sinh sống lâu dài.",["Rộng hơn Củ Chi, đi lại dễ hơn","Mang đèn pin","Thuê hướng dẫn viên nghe kể chuyện"],"Vĩnh Linh, Quảng Trị",17.1000,107.0883,"7:00–17:00","40.000đ","Quanh năm",["địa-đạo","lịch-sử","chiến-tranh","dân-sinh"],false,2),
d("nghia-trang-truong-son","Nghĩa trang Trường Sơn","Nghĩa trang Liệt sĩ Trường Sơn","quang-tri","lich-su","Nghĩa trang liệt sĩ lớn nhất Việt Nam với hơn 10.000 phần mộ.","Nghĩa trang Liệt sĩ Trường Sơn nằm trên đồi Bến Tắt, là nơi yên nghỉ của hơn 10.000 liệt sĩ từ 64 tỉnh thành. Mộ phần được xếp theo tỉnh thành, mỗi khu có bia ghi danh. Đài tưởng niệm trung tâm trang nghiêm. Rừng thông bao phủ tạo không gian thanh tịnh, thiêng liêng.",["Mặc trang phục trang nghiêm","Thắp nhang tưởng niệm","Đến dịp 27/7 để dự lễ"],"Bến Tắt, Gio Linh, Quảng Trị",16.8833,106.9833,"6:00–18:00","Miễn phí","Dịp 27/7",["nghĩa-trang","liệt-sĩ","tưởng-niệm","trường-sơn"],false,3),
// QUẢNG NGÃI (3)
d("dao-ly-son","Đảo Lý Sơn","Đảo Lý Sơn","quang-ngai","thien-nhien","Hòn đảo núi lửa xinh đẹp – \"Maldives Việt Nam\" và vương quốc tỏi.","Đảo Lý Sơn là đảo núi lửa cách đất liền 30km, nổi tiếng với cổng Tò Vò, chùa Hang, cánh đồng tỏi Lý Sơn. Bãi biển nước trong vắt, rêu xanh mướt phủ đá vào mùa xuân. Nơi gắn liền với Đội Hoàng Sa – lịch sử chủ quyền biển đảo. Tỏi Lý Sơn là đặc sản nổi tiếng.",["Thuê xe máy vòng quanh đảo 2h","Ngắm rêu xanh tháng 2–3","Mua tỏi Lý Sơn làm quà"],"Lý Sơn, Quảng Ngãi",15.3850,109.1217,"Luôn mở cửa","Miễn phí","Tháng 2–5",["đảo","núi-lửa","tỏi","biển"],false,1),
d("thanh-co-chau-sa","Thành cổ Châu Sa","Thành cổ Châu Sa","quang-ngai","lich-su","Di tích thành luỹ Chăm Pa cổ lớn nhất còn lại tại miền Trung.","Thành cổ Châu Sa là di tích thành luỹ Chăm Pa (thế kỷ 10–11), chu vi khoảng 4km. Tường thành đất cao 5m còn dấu tích rõ ràng. Là thành phố quan trọng của vương quốc Chăm Pa xưa. Nay nằm giữa đồng ruộng xanh tốt, tạo cảnh quan đặc biệt.",["Kết hợp thăm bảo tàng Quảng Ngãi","Di tích nằm giữa đồng ruộng","Tham quan tự do"],"Tịnh Châu, Sơn Tịnh, Quảng Ngãi",15.1500,108.7667,"Luôn mở cửa","Miễn phí","Quanh năm",["thành-cổ","chăm-pa","lịch-sử","di-tích"],false,2),
d("bai-bien-my-khe-quang-ngai","Bãi biển Mỹ Khê","Bãi biển Mỹ Khê Quảng Ngãi","quang-ngai","thien-nhien","Bãi biển cát trắng dài 7km, yên bình và hoang sơ.","Bãi biển Mỹ Khê Quảng Ngãi dài 7km, cát trắng mịn, nước biển trong xanh. Khác với Mỹ Khê Đà Nẵng, bãi biển này yên bình và hoang sơ hơn nhiều. Ít du khách, phù hợp nghỉ ngơi thư giãn. Gần đó có khu chứng tích Sơn Mỹ.",["Bãi biển yên tĩnh, ít đông","Hải sản tươi giá rẻ","Kết hợp thăm khu chứng tích Sơn Mỹ"],"Tịnh Khê, Sơn Tịnh, Quảng Ngãi",15.1750,108.8833,"Luôn mở cửa","Miễn phí","Tháng 3–8",["biển","hoang-sơ","cát-trắng","yên-tĩnh"],false,3),
// BÌNH ĐỊNH (4)
d("thap-doi","Tháp Đôi","Tháp Đôi","binh-dinh","lich-su","Cặp tháp Chăm cổ đẹp nhất Bình Định giữa lòng thành phố Quy Nhơn.","Tháp Đôi gồm 2 tháp Chăm Pa xây thế kỷ 12 giữa TP. Quy Nhơn. Tháp lớn cao 20m, tháp nhỏ 18m. Kiến trúc gạch Chăm đặc trưng với hoa văn tinh xảo. Là cặp tháp Chăm được trùng tu đẹp nhất Bình Định. Khuôn viên nhỏ nhưng gọn gàng.",["Tham quan nhanh 30 phút","Chụp ảnh lúc nắng chiều","Kết hợp dạo phố Quy Nhơn"],"Trần Hưng Đạo, Quy Nhơn, Bình Định",13.7639,109.2150,"7:00–17:00","Miễn phí","Quanh năm",["tháp-chàm","lịch-sử","kiến-trúc","chăm-pa"],false,1),
d("ghenh-rang","Ghềnh Ráng","Ghềnh Ráng Tiên Sa","binh-dinh","thien-nhien","Bãi đá hoang sơ gắn liền với thi sĩ Hàn Mặc Tử, view biển tuyệt đẹp.","Ghềnh Ráng Tiên Sa nằm phía Nam Quy Nhơn, bãi đá hoang sơ với sóng biển xô bờ. Mộ thi sĩ Hàn Mặc Tử nằm trên đồi thông. Queen's Beach (Bãi Tắm Hoàng Hậu) nhỏ xinh giữa ghềnh đá. Cảnh biển từ trên cao tuyệt đẹp.",["Thăm mộ Hàn Mặc Tử","Tắm tại Queen's Beach","Ngắm bình minh tại ghềnh đá"],"Ghềnh Ráng, Quy Nhơn, Bình Định",13.7333,109.2433,"Luôn mở cửa","20.000đ","Bình minh",["ghềnh-đá","biển","thơ","hoang-sơ"],false,2),
d("ky-co","Kỳ Co","Bãi biển Kỳ Co","binh-dinh","thien-nhien","Bãi biển xanh ngọc bích nằm giữa núi đá, được ví như Maldives Việt Nam.","Kỳ Co là bãi biển nhỏ nằm khuất giữa núi đá, nước xanh ngọc bích trong vắt. Cát trắng mịn, sóng nhẹ, phù hợp tắm biển và lặn ngắm san hô. Đi cano từ Nhơn Lý khoảng 15 phút. Cảnh quan núi đá bao quanh tạo không gian kín đáo, đẹp như thiên đường.",["Đi cano từ Nhơn Lý","Mang kính lặn ngắm san hô","Đặt vé trước vì giới hạn lượng khách"],"Nhơn Lý, Quy Nhơn, Bình Định",13.8667,109.3167,"7:00–16:00","200.000đ (gồm cano)","Tháng 1–8",["biển","ngọc-bích","cano","lặn"],false,3),
d("eo-gio","Eo Gió","Eo Gió","binh-dinh","thien-nhien","Eo biển ngoạn mục nơi gió thổi quanh năm giữa hai vách đá.","Eo Gió là eo biển hẹp giữa hai vách đá dựng đứng ở Nhơn Lý, Quy Nhơn. Gió biển thổi mạnh quanh năm qua eo đá tạo nên tên gọi. Từ trên vách đá ngắm xuống eo biển xanh biếc, sóng xô trắng xoá rất đẹp. Cầu kính mới xây vắt qua eo. Là điểm check-in hot nhất Quy Nhơn.",["Cẩn thận gió mạnh trên vách đá","Chụp ảnh từ cầu kính","Đến sáng sớm ít đông"],"Nhơn Lý, Quy Nhơn, Bình Định",13.8833,109.3233,"6:00–18:00","50.000đ","Sáng sớm",["eo-biển","gió","vách-đá","check-in"],false,4),
// PHÚ YÊN (4)
d("ganh-da-dia","Gành Đá Đĩa","Gành Đá Đĩa","phu-yen","thien-nhien","Kỳ quan thiên nhiên với hàng nghìn cột đá bazan xếp chồng như đĩa khổng lồ.","Gành Đá Đĩa gồm hàng nghìn cột đá bazan hình lăng trụ xếp chồng như đĩa. Hình thành từ dung nham núi lửa nguội lạnh cách đây hàng triệu năm. Tương tự Giant's Causeway (Ireland). Đá đen xám nhẵn bóng nổi bật giữa biển xanh. Là kỳ quan địa chất độc đáo nhất Việt Nam.",["Đến lúc thuỷ triều rút để đi trên đá","Cẩn thận đá trơn khi ướt","Kết hợp thăm bãi Xép gần đó"],"An Ninh Đông, Tuy An, Phú Yên",13.3783,109.3250,"Luôn mở cửa","Miễn phí","Quanh năm",["đá-bazan","địa-chất","kỳ-quan","biển"],false,1),
d("mui-dai","Mũi Đại","Mũi Đại (Mũi Điện)","phu-yen","thien-nhien","Điểm cực Đông – nơi đón ánh bình minh đầu tiên trên đất liền Việt Nam.","Mũi Đại (Mũi Điện) là điểm cực Đông của Việt Nam trên đất liền. Ngọn hải đăng cao 26m (xây 1890) đánh dấu nơi đón bình minh sớm nhất cả nước. Leo 110 bậc thang lên hải đăng ngắm biển bao la. Bãi Môn phía dưới có bãi cát trắng đẹp.",["Đến 4–5h sáng đón bình minh","Leo 110 bậc lên hải đăng","Tắm tại bãi Môn phía dưới"],"Hoà Tâm, Đông Hoà, Phú Yên",12.8833,109.4633,"Luôn mở cửa","20.000đ","Bình minh",["cực-đông","hải-đăng","bình-minh","biển"],false,2),
d("vinh-xuan-dai","Vịnh Xuân Đài","Vịnh Xuân Đài","phu-yen","thien-nhien","Một trong những vịnh đẹp nhất Việt Nam với núi non ôm biển.","Vịnh Xuân Đài hình móng ngựa, rộng khoảng 13.000ha, núi non bao bọc ba phía. Nước vịnh trong xanh, yên tĩnh. Dọc vịnh có nhiều bãi biển nhỏ hoang sơ, làng chài và đầm nuôi hải sản. Đứng từ đèo Quán Cau ngắm toàn cảnh vịnh tuyệt đẹp.",["Ngắm vịnh từ đèo Quán Cau","Ăn hải sản tại làng chài ven vịnh","Đi thuyền trên vịnh"],"Sông Cầu, Phú Yên",13.4333,109.2333,"Luôn mở cửa","Miễn phí","Quanh năm",["vịnh","biển","núi","làng-chài"],false,3),
d("nui-da-bia","Núi Đá Bia","Núi Đá Bia (Thạch Bi Sơn)","phu-yen","thien-nhien","Ngọn núi hùng vĩ cao 706m với khối đá chỉ thiên khổng lồ trên đỉnh.","Núi Đá Bia (Thạch Bi Sơn) cao 706m, trên đỉnh có khối đá khổng lồ hình ngón tay chỉ lên trời. Tương truyền vua Lê Thánh Tông đã khắc chữ trên đá đánh dấu biên giới Đại Việt. Trekking lên đỉnh mất 3–4 giờ qua rừng nguyên sinh. Từ đỉnh ngắm biển Đông và toàn cảnh Phú Yên.",["Trekking 3–4 giờ, cần sức khoẻ","Mang đủ nước và đồ ăn nhẹ","Đi vào sáng sớm"],"Hoà Xuân Nam, Đông Hoà, Phú Yên",12.8667,109.3333,"Luôn mở cửa","Miễn phí","Tháng 1–8",["núi","trekking","đá","chinh-phục"],false,4),
// NINH THUẬN (3)
d("vinh-vinh-hy","Vịnh Vĩnh Hy","Vịnh Vĩnh Hy","ninh-thuan","thien-nhien","Một trong 4 vịnh đẹp nhất Việt Nam với nước xanh ngắt giữa núi đá.","Vịnh Vĩnh Hy nằm trong VQG Núi Chúa, nước xanh ngắt giữa núi đá dựng đứng. Là 1 trong 4 vịnh đẹp nhất VN. Làng chài nhỏ ven vịnh bình yên. San hô phong phú, lặn biển tuyệt vời. Đường đi quanh co ven núi rất đẹp.",["Lặn ngắm san hô","Ăn hải sản tại làng chài","Đường đi quanh co nhưng đẹp"],"Vĩnh Hải, Ninh Hải, Ninh Thuận",11.7133,109.1650,"Luôn mở cửa","Miễn phí","Tháng 1–8",["vịnh","biển","san-hô","làng-chài"],false,1),
d("vuon-quoc-gia-nui-chua","VQG Núi Chúa","Vườn Quốc gia Núi Chúa","ninh-thuan","thien-nhien","Hệ sinh thái bán hoang mạc độc đáo duy nhất tại Việt Nam.","VQG Núi Chúa có hệ sinh thái bán hoang mạc (khô hạn) độc đáo duy nhất Việt Nam. Rừng khộp, xương rồng và cỏ khô tạo cảnh quan lạ mắt. Bãi biển trong VQG là nơi rùa biển đẻ trứng. Nhiều loài quý: voọc, mèo rừng. Khí hậu nắng nóng quanh năm.",["Đi vào mùa mát (tháng 11–3)","Xem rùa đẻ trứng (tháng 6–10)","Mang nhiều nước vì trời nóng"],"Ninh Hải, Ninh Thuận",11.7167,109.1500,"7:00–17:00","40.000đ","Tháng 11–3",["bán-hoang-mạc","rùa-biển","rừng","sinh-thái"],false,2),
d("thap-cham-ninh-thuan","Tháp Chàm Ninh Thuận","Cụm tháp Chàm Po Klong Garai","ninh-thuan","lich-su","Cụm tháp Chăm đẹp nhất còn hoạt động tín ngưỡng, nơi tổ chức lễ Katê.","Tháp Po Klong Garai xây thế kỷ 13–14, là cụm tháp Chăm đẹp nhất và vẫn hoạt động tín ngưỡng. Gồm 3 tháp trên đồi Trầu. Lễ hội Katê (tháng 7 Chăm lịch, ~tháng 10 DL) là lễ hội lớn nhất của người Chăm. Tháp nằm trên đồi, ngắm toàn cảnh Phan Rang.",["Đến dịp lễ hội Katê","Chụp ảnh tháp lúc hoàng hôn","Kết hợp thăm làng Chăm Bàu Trúc"],"Đô Vinh, Phan Rang, Ninh Thuận",11.5733,108.9917,"7:00–17:00","15.000đ","Tháng 10 (Katê)",["tháp-chàm","chăm-pa","katê","lịch-sử"],false,3),
// KON TUM (3)
d("nha-tho-go-kon-tum","Nhà thờ gỗ Kon Tum","Nhà thờ gỗ Kon Tum","kon-tum","van-hoa","Kiệt tác kiến trúc gỗ kết hợp Roman và nhà rông Tây Nguyên.","Nhà thờ gỗ Kon Tum (Nhà thờ Chánh Toà) xây 1913 bằng gỗ cà chít, kiến trúc Roman kết hợp nhà rông Ba Na. Toàn bộ bằng gỗ, không dùng đinh sắt. Cửa sổ kính màu nhập từ Pháp. Khuôn viên có Nhà rông Kon Tum và Cô nhi viện cũ. Là nhà thờ gỗ đẹp nhất Tây Nguyên.",["Chiêm ngưỡng kiến trúc gỗ tinh xảo","Tham quan nhà rông trong khuôn viên","Chụp ảnh sáng sớm hoặc chiều"],"Trần Hưng Đạo, TP. Kon Tum",14.3483,108.0033,"6:00–18:00","Miễn phí","Quanh năm",["nhà-thờ","gỗ","kiến-trúc","tây-nguyên"],false,1),
d("mang-den","Măng Đen","Khu du lịch sinh thái Măng Đen","kon-tum","thien-nhien","\"Đà Lạt thứ hai\" ở độ cao 1.200m với khí hậu mát mẻ và rừng thông.","Măng Đen thuộc huyện Kon Plông, ở độ cao 1.200m, khí hậu mát mẻ quanh năm. Rừng thông bạt ngàn, hồ nước trong xanh. Nhiều thác nước đẹp: thác Pa Sỹ, thác Đắk Ke. Được quy hoạch thành khu du lịch sinh thái quốc gia. Yên bình, ít du khách.",["Mang áo ấm, trời mát lạnh","Trekking đến các thác nước","Rất vắng, phù hợp nghỉ ngơi"],"Kon Plông, Kon Tum",14.7000,108.3167,"Luôn mở cửa","Miễn phí","Quanh năm",["núi","rừng-thông","mát-mẻ","sinh-thái"],false,2),
d("nguc-kon-tum","Ngục Kon Tum","Ngục Kon Tum","kon-tum","lich-su","Di tích lịch sử – nhà tù nơi giam giữ tù chính trị thời Pháp thuộc.","Ngục Kon Tum xây 1930–1931, giam giữ tù chính trị. Nơi đây diễn ra cuộc đấu tranh lưu huyết (12/1931) anh dũng. Nay là bảo tàng trưng bày lịch sử đấu tranh cách mạng Tây Nguyên. Tượng đài tưởng niệm trang nghiêm.",["Tham quan bảo tàng","Nghe thuyết minh về lịch sử","Kết hợp thăm nhà thờ gỗ"],"Trần Phú, TP. Kon Tum",14.3500,108.0050,"7:30–17:00","Miễn phí","Quanh năm",["nhà-tù","lịch-sử","bảo-tàng","cách-mạng"],false,3),
// GIA LAI (3)
d("bien-ho","Biển Hồ","Biển Hồ (Hồ T'Nưng)","gia-lai","thien-nhien","Hồ nước ngọt trong miệng núi lửa cổ, đẹp huyền bí giữa cao nguyên.","Biển Hồ (T'Nưng) là hồ nước ngọt tự nhiên trong miệng núi lửa đã tắt, rộng 230ha, sâu 40m. Nước hồ xanh biếc quanh năm, bao quanh bởi rừng thông. Truyền thuyết kể về ngôi làng bị nhấn chìm. Hồ cung cấp nước cho TP. Pleiku. Sáng sớm sương mù phủ hồ rất đẹp.",["Ngắm hồ lúc sáng sớm có sương","Café ven hồ thưởng thức view","Đường vào hồ qua rừng thông đẹp"],"TP. Pleiku, Gia Lai",14.0333,108.0167,"Luôn mở cửa","Miễn phí","Sáng sớm",["hồ","núi-lửa","sương-mù","huyền-bí"],false,1),
d("thac-phu-cuong","Thác Phú Cường","Thác Phú Cường","gia-lai","thien-nhien","Thác nước hùng vĩ giữa đồi thông xanh ngát, đẹp nhất Gia Lai.","Thác Phú Cường nằm cách Pleiku 45km, nước đổ từ cao 45m xuống vực sâu giữa rừng thông. Mùa mưa thác hùng vĩ với lượng nước lớn. Xung quanh là đồi thông xanh ngát. Bên dưới có hồ nước trong veo. Là thác đẹp nhất Gia Lai.",["Mùa mưa thác đẹp nhất (tháng 7–10)","Cẩn thận đường trơn","Mang áo mưa vì hơi nước"],"Chư Sê, Gia Lai",13.7833,108.0667,"7:00–17:00","10.000đ","Tháng 7–10",["thác","đồi-thông","thiên-nhiên","hùng-vĩ"],false,2),
d("nha-tho-duc-an","Nhà thờ Đức An","Nhà thờ Đức An","gia-lai","van-hoa","Nhà thờ kiến trúc nhà rông Tây Nguyên độc đáo giữa TP. Pleiku.","Nhà thờ Đức An (Plei Chuet) có kiến trúc độc đáo theo phong cách nhà rông Tây Nguyên – mái nhọn cao vút. Bên trong trang trí hoạ tiết thổ cẩm Ba Na, Jrai. Kết hợp hài hoà giữa tín ngưỡng Công giáo và văn hoá bản địa. Là công trình kiến trúc tôn giáo đặc biệt.",["Chiêm ngưỡng kiến trúc nhà rông","Xem hoạ tiết thổ cẩm bên trong","Kết hợp uống café Pleiku"],"Nguyễn Viết Xuân, Pleiku, Gia Lai",13.9833,108.0000,"6:00–18:00","Miễn phí","Quanh năm",["nhà-thờ","nhà-rông","kiến-trúc","tây-nguyên"],false,3),
// ĐẮK LẮK (4)
d("ho-lak","Hồ Lắk","Hồ Lắk","dak-lak","thien-nhien","Hồ nước ngọt tự nhiên lớn thứ 2 Tây Nguyên với buôn làng M'Nông.","Hồ Lắk rộng 6km², lớn thứ 2 Tây Nguyên, nằm giữa núi rừng. Xung quanh là buôn làng M'Nông với nhà dài truyền thống. Biệt điện Bảo Đại bên hồ. Du khách đi thuyền độc mộc, cưỡi voi và trải nghiệm văn hoá M'Nông. Mùa mưa hồ đẹp nhất.",["Đi thuyền độc mộc trên hồ","Ở nhà dài M'Nông","Xem cồng chiêng buổi tối"],"Lắk, Đắk Lắk",12.3833,108.1833,"Luôn mở cửa","Thuyền: 50.000đ","Tháng 10–3",["hồ","dân-tộc","nhà-dài","thuyền"],false,1),
d("buon-don","Buôn Đôn","Buôn Đôn","dak-lak","van-hoa","Vùng đất thuần dưỡng voi với văn hoá dân tộc Ê Đê đặc sắc.","Buôn Đôn nổi tiếng với truyền thống thuần dưỡng voi rừng của người M'Nông, Ê Đê. Khu du lịch có bảo tàng voi, cầu treo tre và biệt thự trên cây. Du khách tham quan buôn làng, tìm hiểu nghề nuôi voi truyền thống. VQG Yok Đôn gần đó có rừng khộp lớn nhất VN.",["Tìm hiểu văn hoá voi tại bảo tàng","Đi cầu treo tre","Thăm VQG Yok Đôn gần đó"],"Buôn Đôn, Đắk Lắk",12.9000,107.7333,"7:00–17:00","30.000đ","Tháng 11–4",["voi","dân-tộc","buôn-làng","cầu-treo"],false,2),
d("thac-dray-nur","Thác Drây Nur","Thác Drây Nur","dak-lak","thien-nhien","Thác nước hùng vĩ nhất Tây Nguyên trên sông Sêrêpốk.","Thác Drây Nur (thác Chồng) nằm trên sông Sêrêpốk, rộng 250m, cao 30m. Mùa mưa nước đổ xuống ầm ầm, tung bọt trắng xoá rất hùng vĩ. Đối diện là thác Drây Sáp (thác Vợ). Cầu treo bắc qua sông ngắm thác. Xung quanh rừng cây xanh mát.",["Mùa mưa (tháng 7–10) thác đẹp nhất","Đi cầu treo ngắm thác","Kết hợp thăm thác Drây Sáp"],"Krông Ana, Đắk Lắk",12.6167,108.0167,"7:00–17:00","30.000đ","Tháng 7–10",["thác","sông","hùng-vĩ","cầu-treo"],false,3),
d("bao-tang-dak-lak","Bảo tàng Đắk Lắk","Bảo tàng tỉnh Đắk Lắk","dak-lak","van-hoa","Bảo tàng kiến trúc hiện đại nhất Tây Nguyên về văn hoá cồng chiêng.","Bảo tàng Đắk Lắk nằm trung tâm TP. Buôn Ma Thuột, kiến trúc hiện đại kết hợp truyền thống. Trưng bày phong phú về văn hoá cồng chiêng, đời sống dân tộc Ê Đê, M'Nông. Bộ sưu tập nhạc cụ Tây Nguyên đa dạng. Khu trưng bày cà phê thú vị. Sân ngoài có nhà dài Ê Đê.",["Dành 2 giờ tham quan","Xem nhà dài Ê Đê ngoài sân","Thưởng cà phê Buôn Ma Thuột"],"Nguyễn Du, Buôn Ma Thuột, Đắk Lắk",12.6833,108.0500,"7:30–17:00 (đóng cửa T2)","10.000đ","Quanh năm",["bảo-tàng","cồng-chiêng","cà-phê","dân-tộc"],false,4),
// ĐẮK NÔNG (3)
d("ta-dung","Hồ Tà Đùng","Hồ Tà Đùng","dak-nong","thien-nhien","\"Vịnh Hạ Long Tây Nguyên\" với hàng trăm đảo nhỏ giữa hồ xanh biếc.","Hồ Tà Đùng là hồ thuỷ điện rộng 22.000ha, có hơn 40 đảo lớn nhỏ nhô lên giữa mặt nước xanh biếc. Được ví \"Vịnh Hạ Long của Tây Nguyên\". Sáng sớm sương mù phủ hồ rất đẹp. Cắm trại ven hồ, chèo thuyền kayak giữa các đảo. Phong cảnh hoang sơ, yên bình.",["Cắm trại qua đêm ven hồ","Ngắm bình minh trên hồ","Chèo kayak giữa các đảo"],"Đắk Som, Đắk G'Long, Đắk Nông",11.8833,107.9833,"Luôn mở cửa","Miễn phí","Quanh năm",["hồ","đảo","camping","hoang-sơ"],false,1),
d("thac-dray-sap","Thác Drây Sáp","Thác Drây Sáp – Gia Long","dak-nong","thien-nhien","Cụm thác đôi hùng vĩ trên sông Sêrêpốk giữa rừng nguyên sinh.","Thác Drây Sáp (thác Khói) cao 20m, rộng 100m trên sông Sêrêpốk. Nước đổ tung bọt như khói (Drây Sáp = thác Khói theo tiếng Ê Đê). Gần đó là thác Gia Long nhỏ hơn nhưng đẹp. Rừng cây cổ thụ bao quanh, không khí mát mẻ.",["Mùa mưa thác lớn nhất","Đi bộ giữa 2 thác mất 30 phút","Mang áo mưa"],"Đắk R'Tih, Tuy Đức, Đắk Nông",12.5667,107.9833,"7:00–17:00","30.000đ","Tháng 7–10",["thác","sông","rừng","thiên-nhiên"],false,2),
d("cong-vien-dia-chat-dak-nong","Công viên Địa chất Đắk Nông","Công viên Địa chất Toàn cầu UNESCO Đắk Nông","dak-nong","thien-nhien","CVĐC UNESCO với hệ thống hang động núi lửa độc đáo nhất ĐNA.","Công viên Địa chất Đắk Nông được UNESCO công nhận 2020. Nổi bật là hệ thống hang động núi lửa dài nhất ĐNA (hàng km). Hang C7 và hang Doi là hang lớn nhất. Miệng núi lửa Chư B'Luk nguyên vẹn. Ngoài địa chất còn có giá trị văn hoá, lịch sử của người M'Nông.",["Thăm hang động núi lửa C7","Mang đèn pin tốt","Thuê hướng dẫn viên"],"Krông Nô, Đắk Nông",12.5000,107.8000,"7:00–17:00","30.000đ","Tháng 11–4",["hang-động","núi-lửa","địa-chất","unesco"],false,3),
];

const op=path.join(__dirname,'../src/data/destinations-trung-2.json');
fs.writeFileSync(op,JSON.stringify(dests,null,2),'utf-8');
console.log(`Generated ${dests.length} Miền Trung (part 2) destinations`);
