const fs=require('fs'),path=require('path');
let imgC=3000;
function img(){imgC++;return`https://images.unsplash.com/photo-160059654${imgC}-${imgC}ab${imgC}cd?w=800&h=600&fit=crop&auto=format`;}
function d(s,n,nv,p,c,desc,ld,tips,addr,lat,lng,h,f,bt,tags,ft,o){
return{id:s,slug:s,name:n,nameVi:nv,provinceSlug:p,category:c,description:desc,longDescription:ld,
images:[{src:img(),alt:n,caption:`${n} – cảnh đẹp`},{src:img(),alt:`${n} view`,caption:`Khung cảnh tại ${n}`}],
tips,address:addr,coordinates:{lat,lng},openingHours:h,entryFee:f,bestTimeToVisit:bt,tags,featured:ft,order:o};}

const dests=[
// DA NANG (6)
d("cau-vang-ba-na","Cầu Vàng Bà Nà Hills","Cầu Vàng (Golden Bridge)","da-nang","giai-tri","Cây cầu vàng được nâng đỡ bởi đôi bàn tay khổng lồ, biểu tượng du lịch Việt Nam.","Cầu Vàng nằm trong khu du lịch Bà Nà Hills, dài 150m được nâng đỡ bởi hai bàn tay đá khổng lồ giữa mây trời. Khu du lịch còn có làng Pháp, vườn hoa Le Jardin D'Amour và Fantasy Park. Hệ thống cáp treo đạt kỷ lục thế giới.",["Đi ngày thường tránh đông","Mang áo ấm vì trên núi lạnh","Mua vé trọn gói"],"Hoà Ninh, Hoà Vang, Đà Nẵng",15.9977,107.9881,"7:00–22:00","900.000đ","Tháng 3–9",["cầu","khu-du-lịch","check-in","núi"],true,1),
d("bai-bien-my-khe","Bãi biển Mỹ Khê","Bãi biển Mỹ Khê","da-nang","thien-nhien","Một trong 6 bãi biển quyến rũ nhất hành tinh theo Forbes.","Mỹ Khê dài hơn 900m, cát trắng mịn, nước trong xanh. Lý tưởng cho tắm biển, lướt ván. Dọc biển có resort, nhà hàng hải sản. Là bãi biển gần trung tâm nhất.",["Tắm sáng 5–7h hoặc chiều 15–17h","Có dịch vụ thuê dù ghế","Thử hải sản ven biển"],"Võ Nguyên Giáp, Sơn Trà, Đà Nẵng",16.0583,108.2452,"Luôn mở cửa","Miễn phí","Tháng 5–8",["biển","cát-trắng","thể-thao"],false,2),
d("ngu-hanh-son","Ngũ Hành Sơn","Ngũ Hành Sơn (Marble Mountains)","da-nang","tam-linh","Cụm 5 ngọn núi đá vôi với chùa chiền, hang động huyền bí.","5 ngọn núi Kim Mộc Thuỷ Hoả Thổ bằng đá vôi và cẩm thạch. Có chùa cổ kính, hang động Huyền Không thần bí. Đỉnh núi ngắm toàn cảnh Đà Nẵng. Dưới chân là làng nghề đá Non Nước.",["Mang giày thoải mái leo bậc thang","Đi sáng sớm tránh nóng","Có thang máy lên núi Thuỷ Sơn"],"Huyền Trân Công Chúa, Ngũ Hành Sơn, Đà Nẵng",16.0040,108.2633,"7:00–17:30","40.000đ","Sáng sớm",["núi","chùa","hang-động","tâm-linh"],false,3),
d("ban-dao-son-tra","Bán đảo Sơn Trà","Bán đảo Sơn Trà","da-nang","thien-nhien","Khu bảo tồn thiên nhiên với loài voọc chà vá chân nâu quý hiếm và chùa Linh Ứng.","Bán đảo Sơn Trà rộng 4.439ha, là lá phổi xanh của Đà Nẵng. Nơi sinh sống của loài voọc chà vá chân nâu – linh trưởng đẹp nhất thế giới. Chùa Linh Ứng có tượng Quan Âm cao 67m. Đỉnh Bàn Cờ ngắm toàn cảnh thành phố và biển.",["Thuê xe máy đi quanh bán đảo","Ngắm voọc vào sáng sớm","Ghé chùa Linh Ứng và tượng Quan Âm"],"Bán đảo Sơn Trà, Đà Nẵng",16.1167,108.2667,"Luôn mở cửa","Miễn phí","Tháng 2–8",["bán-đảo","voọc","chùa","rừng"],false,4),
d("cau-rong","Cầu Rồng","Cầu Rồng","da-nang","lich-su","Cầu hình rồng dài 666m, phun lửa và nước mỗi tối cuối tuần.","Cầu Rồng bắc qua sông Hàn, dài 666m với thiết kế hình rồng uốn lượn. Mỗi tối thứ 7 và Chủ nhật 21h, rồng phun lửa và nước – show diễn miễn phí hấp dẫn. Cầu là biểu tượng kiến trúc hiện đại của Đà Nẵng, nối trung tâm với bãi biển Mỹ Khê.",["Xem phun lửa/nước tối T7 CN 21h","Đứng phía đầu rồng để thấy rõ nhất","Kết hợp dạo bờ sông Hàn"],"Cầu Rồng, Đà Nẵng",16.0610,108.2277,"Luôn mở cửa","Miễn phí","Tối T7, CN",["cầu","biểu-tượng","phun-lửa","đêm"],false,5),
d("cho-han","Chợ Hàn","Chợ Hàn","da-nang","van-hoa","Khu chợ truyền thống sầm uất nhất Đà Nẵng với đặc sản miền Trung.","Chợ Hàn nằm bên bờ sông Hàn, là chợ truyền thống lớn nhất Đà Nẵng. Bán đủ loại hàng hoá từ quần áo, đồ lưu niệm đến đặc sản miền Trung. Tầng 2 có khu ẩm thực với mì Quảng, bún chả cá, bánh tráng cuốn thịt heo. Giá cả phải chăng hơn so với khu du lịch.",["Trả giá khi mua hàng","Thử mì Quảng và bún chả cá tầng 2","Đến buổi sáng để mua hải sản tươi"],"Đường Trần Phú, Hải Châu, Đà Nẵng",16.0680,108.2240,"6:00–18:00","Miễn phí","Sáng sớm",["chợ","ẩm-thực","mua-sắm","đặc-sản"],false,6),
// THỪA THIÊN HUẾ (6)
d("dai-noi-hue","Đại Nội Huế","Đại Nội Huế (Tử Cấm Thành)","thua-thien-hue","lich-su","Di sản Văn hoá Thế giới UNESCO – Hoàng cung triều Nguyễn uy nghi, tráng lệ.","Đại Nội Huế là kinh thành của triều Nguyễn (1802–1945), gồm Kinh Thành, Hoàng Thành và Tử Cấm Thành. Được UNESCO công nhận năm 1993. Nổi bật: Ngọ Môn, Điện Thái Hoà, cung Trường Sanh, Duyệt Thị Đường. Diện tích 520ha với hào nước bao quanh.",["Dành ít nhất 3 giờ tham quan","Thuê hướng dẫn viên","Mặc áo dài chụp ảnh miễn phí"],"Thuận Thành, TP. Huế",16.4698,107.5784,"7:00–17:30","200.000đ","Tháng 1–4",["di-sản-unesco","hoàng-cung","kiến-trúc","triều-nguyễn"],true,1),
d("chua-thien-mu","Chùa Thiên Mụ","Chùa Thiên Mụ","thua-thien-hue","tam-linh","Ngôi chùa cổ nhất Huế với tháp Phước Duyên 7 tầng bên bờ sông Hương.","Chùa Thiên Mụ xây năm 1601, là ngôi chùa cổ nhất và biểu tượng của Huế. Tháp Phước Duyên 7 tầng cao 21m nổi bật bên bờ sông Hương. Chùa có đại hồng chung nặng 2 tấn và chiếc xe Austin của Hoà thượng Thích Quảng Đức. Cảnh quan sông Hương từ chùa rất thơ mộng.",["Đi thuyền trên sông Hương đến chùa","Ngắm hoàng hôn từ chùa","Mặc trang phục kín đáo"],"Hương Hoà, TP. Huế",16.4539,107.5487,"6:00–18:00","Miễn phí","Chiều hoàng hôn",["chùa","tháp","sông-hương","biểu-tượng"],false,2),
d("lang-tu-duc","Lăng Tự Đức","Lăng Tự Đức","thua-thien-hue","lich-su","Lăng tẩm đẹp nhất Huế với kiến trúc thơ mộng giữa rừng thông.","Lăng Tự Đức xây 1864–1867, rộng 12ha, là lăng đẹp nhất trong các lăng vua Nguyễn. Vua Tự Đức tự thiết kế lăng thành nơi nghỉ ngơi, sáng tác thơ văn khi còn sống. Có hồ Lưu Khiêm thơ mộng, đảo Tịnh Khiêm trồng hoa sen. Kiến trúc hài hoà với thiên nhiên rừng thông.",["Kết hợp thăm lăng Khải Định gần đó","Dành 1–2 giờ tham quan","Thuê áo dài chụp ảnh"],"Thuỷ Xuân, TP. Huế",16.4585,107.5718,"7:00–17:30","100.000đ","Sáng sớm",["lăng","kiến-trúc","triều-nguyễn","thơ-mộng"],false,3),
d("lang-khai-dinh","Lăng Khải Định","Lăng Khải Định","thua-thien-hue","lich-su","Lăng tẩm kiến trúc Đông Tây kết hợp, nội thất khảm sành sứ lộng lẫy.","Lăng Khải Định xây 1920–1931, kiến trúc pha trộn Đông – Tây độc đáo với bê tông cốt thép và trang trí cổ điển. Nội thất cung Thiên Định khảm sành sứ và thuỷ tinh lộng lẫy. Tượng đồng vua Khải Định ngồi trên ngai đúc tại Pháp. Lăng nhỏ nhưng tinh xảo nhất.",["Chiêm ngưỡng nội thất khảm sành sứ","Kết hợp thăm lăng Tự Đức","Leo 127 bậc thang lên lăng"],"Thuỷ Bằng, TP. Huế",16.3952,107.5803,"7:00–17:30","100.000đ","Sáng",["lăng","kiến-trúc","khảm-sứ","triều-nguyễn"],false,4),
d("cau-truong-tien","Cầu Trường Tiền","Cầu Trường Tiền","thua-thien-hue","lich-su","Cây cầu biểu tượng của Huế bắc qua sông Hương, lung linh đèn màu về đêm.","Cầu Trường Tiền xây năm 1899, dài 402m với 6 nhịp cong bằng thép, thiết kế bởi Gustave Eiffel. Là biểu tượng của Huế bắc qua sông Hương thơ mộng. Buổi tối, cầu lung linh với hệ thống đèn LED đổi màu. Dạo bờ sông Hương qua cầu Trường Tiền là trải nghiệm lãng mạn nhất Huế.",["Ngắm cầu về đêm với đèn LED","Dạo bờ sông Hương từ cầu","Ăn chè Huế gần cầu"],"Cầu Trường Tiền, TP. Huế",16.4681,107.5955,"Luôn mở cửa","Miễn phí","Tối (ngắm đèn)",["cầu","biểu-tượng","sông-hương","đêm"],false,5),
d("nui-bach-ma","Núi Bạch Mã","Vườn Quốc gia Bạch Mã","thua-thien-hue","thien-nhien","Khu nghỉ mát Pháp cổ trên đỉnh núi 1.450m với khí hậu mát mẻ và thác nước đẹp.","VQG Bạch Mã nằm trên dãy Trường Sơn, đỉnh cao 1.450m. Từng là khu nghỉ mát của người Pháp, nay còn phế tích biệt thự. Thác Đỗ Quyên, Ngũ Hồ tuyệt đẹp. Rừng nguyên sinh phong phú, khí hậu mát mẻ quanh năm. Là điểm trekking lý tưởng giữa miền Trung.",["Mang áo ấm, đỉnh núi lạnh","Trekking đến thác Đỗ Quyên","Thuê xe jeep lên đỉnh"],"Phú Lộc, Thừa Thiên Huế",16.2067,107.8567,"6:00–17:00","60.000đ","Tháng 2–9",["núi","rừng","thác","trekking"],false,6),
// QUẢNG NAM (5)
d("pho-co-hoi-an","Phố cổ Hội An","Phố cổ Hội An","quang-nam","van-hoa","Di sản Văn hoá Thế giới UNESCO – đô thị cổ lung linh đèn lồng mỗi đêm rằm.","Phố cổ Hội An là đô thị cổ được bảo tồn nguyên vẹn nhất Đông Nam Á, UNESCO công nhận năm 1999. Kiến trúc pha trộn Việt – Hoa – Nhật với nhà cổ, hội quán, chùa miếu. Đêm rằm, phố cổ thả đèn hoa đăng trên sông Hoài lung linh. Ẩm thực: cao lầu, mì Quảng, bánh mì Phượng.",["Đến vào đêm rằm thả đèn hoa đăng","Thuê áo dài đi dạo phố cổ","Ăn cao lầu và bánh mì Phượng"],"Phố cổ Hội An, Quảng Nam",15.8801,108.3380,"Luôn mở cửa (vé: 7–21h)","120.000đ (5 điểm)","Đêm rằm hàng tháng",["phố-cổ","đèn-lồng","di-sản-unesco","ẩm-thực"],true,1),
d("thanh-dia-my-son","Thánh địa Mỹ Sơn","Thánh địa Mỹ Sơn","quang-nam","lich-su","Di sản UNESCO – quần thể đền tháp Chăm Pa huyền bí giữa thung lũng xanh.","Thánh địa Mỹ Sơn gồm hơn 70 công trình kiến trúc Chăm Pa (thế kỷ 4–13), UNESCO công nhận năm 1999. Các tháp xây bằng gạch nung không dùng chất kết dính – bí ẩn chưa giải mã. Nằm trong thung lũng hẹp bao quanh bởi đồi núi xanh. Show nghệ thuật Chăm biểu diễn hàng ngày.",["Đi sớm 7–8h tránh nắng","Xem show nghệ thuật Chăm","Thuê hướng dẫn viên"],"Duy Phú, Duy Xuyên, Quảng Nam",15.7644,108.1257,"6:00–17:00","150.000đ","Sáng sớm",["di-sản-unesco","chăm-pa","tháp","lịch-sử"],false,2),
d("chua-cau-hoi-an","Chùa Cầu Hội An","Chùa Cầu (Cầu Nhật Bản)","quang-nam","van-hoa","Biểu tượng của Hội An – cây cầu cổ 400 năm do thương nhân Nhật Bản xây dựng.","Chùa Cầu xây dựng đầu thế kỷ 17 bởi cộng đồng thương nhân Nhật Bản, nối liền khu phố Nhật và phố Hoa. Cầu có mái che kiểu Nhật Bản, giữa cầu có chùa nhỏ thờ Bắc Đế Trấn Vũ. In trên tờ tiền polymer 20.000đ của Việt Nam. Là điểm check-in biểu tượng của Hội An.",["Chụp ảnh lúc vắng người: sáng sớm","In trên tờ 20.000đ – mang theo so sánh","Tham quan miễn phí bên ngoài"],"Nguyễn Thị Minh Khai, Hội An",15.8775,108.3272,"7:00–21:00","Gồm trong vé phố cổ","Sáng sớm",["cầu","biểu-tượng","nhật-bản","phố-cổ"],false,3),
d("cu-lao-cham","Cù Lao Chàm","Cù Lao Chàm","quang-nam","thien-nhien","Khu dự trữ Sinh quyển Thế giới UNESCO với biển trong vắt và san hô đa dạng.","Cù Lao Chàm gồm 8 đảo ngoài khơi Hội An, được UNESCO công nhận Khu dự trữ Sinh quyển. Biển trong vắt, san hô phong phú, lý tưởng cho lặn biển. Bãi Hương, bãi Ông có cát trắng sạch. Đảo có làng chài cổ, đền chùa cổ kính. Nổi tiếng từ bỏ rác thải nhựa.",["Đi ca nô từ Cửa Đại (20 phút)","Lặn biển ngắm san hô","Thử hải sản tươi trên đảo"],"Cù Lao Chàm, Hội An, Quảng Nam",15.9483,108.4967,"Theo tour","Vé: 70.000đ + ca nô 250.000đ","Tháng 3–8",["đảo","lặn-biển","san-hô","sinh-quyển"],false,4),
d("lang-rau-tra-que","Làng rau Trà Quế","Làng rau Trà Quế","quang-nam","van-hoa","Làng rau hữu cơ 400 năm tuổi, nơi du khách trải nghiệm làm nông dân.","Làng Trà Quế cách Hội An 3km, trồng rau hữu cơ 400 năm bằng phương pháp truyền thống bón rong biển. Du khách được trải nghiệm cuốc đất, gieo hạt, tưới nước như nông dân thực thụ. Sau đó học nấu ăn với rau vừa hái. Tour trải nghiệm nửa ngày rất phổ biến.",["Đặt tour trải nghiệm nửa ngày","Mang giày chống lấm","Thử món salad rau Trà Quế"],"Trà Quế, Cẩm Hà, Hội An",15.9000,108.3300,"7:00–17:00","Tour: 300.000–500.000đ","Quanh năm",["làng-rau","trải-nghiệm","hữu-cơ","nấu-ăn"],false,5),
// KHÁNH HOÀ (5)
d("vinh-nha-trang","Vịnh Nha Trang","Vịnh Nha Trang","khanh-hoa","thien-nhien","Một trong 29 vịnh đẹp nhất thế giới với biển xanh trong và nhiều đảo.","Vịnh Nha Trang có 19 đảo lớn nhỏ, nước biển trong xanh, hệ san hô phong phú. Là 1 trong 29 vịnh đẹp nhất thế giới. Bãi biển Nha Trang dài 7km ven thành phố. Tour 4 đảo là trải nghiệm phổ biến nhất: Hòn Mun, Hòn Một, Hòn Tằm, Hòn Miễu.",["Tour 4 đảo nửa ngày rất vui","Lặn biển ở Hòn Mun","Tắm biển tại bãi trung tâm miễn phí"],"TP. Nha Trang, Khánh Hoà",12.2388,109.1967,"Luôn mở cửa","Tour 4 đảo: 200.000đ","Tháng 1–8",["vịnh","biển","đảo","lặn-biển"],true,1),
d("thap-ba-ponagar","Tháp Bà Ponagar","Tháp Bà Ponagar","khanh-hoa","lich-su","Kiệt tác kiến trúc Chăm Pa hơn 1.000 năm tuổi trên đồi nhìn ra sông Cái.","Tháp Bà Ponagar xây dựng từ thế kỷ 8–13, thờ nữ thần Ponagar – Mẹ xứ sở của người Chăm. Quần thể gồm 4 tháp trên đồi cao nhìn ra sông Cái. Tháp chính cao 23m, kiến trúc gạch tinh xảo. Lễ hội Tháp Bà tháng 3 âm lịch thu hút đông đảo du khách.",["Đến sáng sớm để tránh nắng","Mặc trang phục kín đáo","Xem lễ hội tháng 3 âm lịch"],"Vĩnh Phước, Nha Trang",12.2656,109.1953,"6:00–18:00","22.000đ","Sáng sớm",["tháp-chàm","lịch-sử","kiến-trúc","chăm-pa"],false,2),
d("vinpearl-nha-trang","Vinpearl Nha Trang","Vinpearl Land Nha Trang","khanh-hoa","giai-tri","Khu giải trí lớn trên Hòn Tre với công viên nước, thuỷ cung và cáp treo.","Vinpearl Land nằm trên đảo Hòn Tre, kết nối với đất liền bằng cáp treo dài 3.320m vượt biển. Khu giải trí gồm công viên nước, thuỷ cung Underwater World, vườn thú, khu trò chơi và bãi biển riêng. Buổi tối có show nhạc nước hoành tráng. Lý tưởng cho gia đình có trẻ em.",["Dành cả ngày để trải nghiệm đủ","Đi cáp treo ngắm biển tuyệt đẹp","Xem show nhạc nước buổi tối"],"Hòn Tre, Vĩnh Nguyên, Nha Trang",12.2267,109.2333,"8:30–21:00","880.000đ (gồm cáp treo)","Quanh năm",["giải-trí","cáp-treo","công-viên-nước","gia-đình"],false,3),
d("hon-mun","Hòn Mun","Khu bảo tồn biển Hòn Mun","khanh-hoa","thien-nhien","Khu bảo tồn biển đầu tiên của Việt Nam với hệ san hô phong phú nhất.","Hòn Mun là khu bảo tồn biển đầu tiên của Việt Nam (2001), có hơn 350 loài san hô cứng – phong phú nhất cả nước. Nước biển trong vắt, tầm nhìn xa 15–20m. Lặn biển (scuba diving và snorkeling) ngắm san hô và cá nhiệt đới là trải nghiệm tuyệt vời. Khu vực được bảo vệ nghiêm ngặt.",["Lặn snorkeling hoặc scuba diving","Không chạm vào san hô","Đi tour từ bến Nha Trang"],"Hòn Mun, Nha Trang, Khánh Hoà",12.1683,109.2717,"Theo tour","150.000đ (vé bảo tồn)","Tháng 3–9",["lặn-biển","san-hô","bảo-tồn","đảo"],false,4),
d("dao-diep-son","Đảo Điệp Sơn","Đảo Điệp Sơn","khanh-hoa","thien-nhien","Hòn đảo nổi tiếng với con đường đi bộ giữa biển nối 3 đảo.","Đảo Điệp Sơn thuộc vịnh Vân Phong, nổi tiếng với con đường cát nổi giữa biển dài 700m nối 3 hòn đảo nhỏ. Khi thuỷ triều rút, đường cát lộ ra tạo cảnh tượng kỳ thú – đi bộ giữa biển. Đảo hoang sơ, ít dịch vụ, phù hợp cho trải nghiệm Robinson. Phải kiểm tra thuỷ triều trước khi đi.",["Kiểm tra giờ thuỷ triều rút","Mang theo đồ ăn, nước uống","Đi ca nô từ Vạn Giã"],"Vạn Thạnh, Vạn Ninh, Khánh Hoà",12.5550,109.2400,"Theo thuỷ triều","Ca nô: 100.000đ","Tháng 1–8",["đảo","đường-biển","hoang-sơ","thuỷ-triều"],false,5),
// LÂM ĐỒNG (5)
d("thanh-pho-da-lat","Thành phố Đà Lạt","Thành phố Đà Lạt","lam-dong","van-hoa","Thành phố ngàn hoa ở độ cao 1.500m với khí hậu mát mẻ và biệt thự Pháp lãng mạn.","Đà Lạt ở độ cao 1.500m, khí hậu mát mẻ quanh năm 18–25°C. Thành phố có kiến trúc biệt thự Pháp cổ, vườn hoa rực rỡ và hồ Xuân Hương thơ mộng. Chợ Đà Lạt, ga Đà Lạt cổ kính. Nổi tiếng với cà phê, atiso, dâu tây và rau hoa xứ lạnh.",["Mang áo ấm, tối lạnh","Thuê xe máy đi quanh thành phố","Uống cà phê view đồi thông"],"TP. Đà Lạt, Lâm Đồng",11.9404,108.4583,"Luôn mở cửa","Miễn phí","Tháng 11–3",["thành-phố","hoa","biệt-thự-pháp","mát-mẻ"],true,1),
d("ho-xuan-huong","Hồ Xuân Hương","Hồ Xuân Hương","lam-dong","thien-nhien","Hồ nước thơ mộng giữa lòng Đà Lạt, biểu tượng của thành phố ngàn hoa.","Hồ Xuân Hương nằm giữa trung tâm Đà Lạt, chu vi khoảng 5km. Xung quanh hồ là rừng thông, vườn hoa và biệt thự cổ. Buổi sáng, sương mù phủ trên mặt hồ rất đẹp. Du khách đạp xe quanh hồ, đạp vịt, hoặc đi bộ ngắm cảnh. Đây là trái tim và biểu tượng của Đà Lạt.",["Đạp xe quanh hồ buổi sáng sớm","Ngắm sương mù trên hồ","Đạp vịt trên hồ – trải nghiệm kinh điển"],"Hồ Xuân Hương, TP. Đà Lạt",11.9380,108.4420,"Luôn mở cửa","Miễn phí (đạp vịt: 50.000đ)","Sáng sớm",["hồ","biểu-tượng","đạp-xe","sương-mù"],false,2),
d("thung-lung-tinh-yeu","Thung Lũng Tình Yêu","Thung Lũng Tình Yêu","lam-dong","thien-nhien","Thung lũng lãng mạn với hồ nước, đồi thông và vườn hoa muôn sắc.","Thung Lũng Tình Yêu nằm cách trung tâm 5km, là khu du lịch lâu đời nhất Đà Lạt. Hồ Đa Thiện thơ mộng giữa thung lũng đồi thông. Vườn hoa muôn sắc nở quanh năm. Là nơi lý tưởng cho các cặp đôi chụp ảnh cưới và tham quan. Có xe ngựa, xe đạp nước.",["Đến sáng sớm ít đông","Mua vé kết hợp với các điểm khác","Chụp ảnh tại cầu gỗ trên hồ"],"Phường 8, TP. Đà Lạt",11.9632,108.4390,"7:00–17:00","100.000đ","Quanh năm",["thung-lũng","hoa","hồ","lãng-mạn"],false,3),
d("dinh-bao-dai","Dinh Bảo Đại","Dinh III (Dinh Bảo Đại)","lam-dong","lich-su","Dinh thự mùa hè của vua Bảo Đại với kiến trúc Art Deco giữa rừng thông.","Dinh III (Dinh Bảo Đại) xây năm 1933, là nơi nghỉ hè của vị vua cuối cùng triều Nguyễn. Kiến trúc Art Deco Pháp giữa rừng thông và vườn hoa. Nội thất giữ nguyên: phòng làm việc, phòng ngủ, bàn tiệc. Từ sân thượng ngắm toàn cảnh Đà Lạt.",["Tham quan nội thất nguyên bản","Mặc áo dài hoàng gia chụp ảnh","Kết hợp thăm Dinh I, Dinh II"],"Triệu Việt Vương, Phường 4, Đà Lạt",11.9417,108.4300,"7:00–17:00","40.000đ","Sáng",["dinh-thự","bảo-đại","lịch-sử","kiến-trúc"],false,4),
d("thac-datanla","Thác Datanla","Thác Datanla","lam-dong","thien-nhien","Thác nước nổi tiếng với trò trượt máng và canyoning mạo hiểm.","Thác Datanla cách trung tâm Đà Lạt 5km, là thác nước đẹp nằm trong rừng thông. Nổi tiếng với trò trượt máng (Alpine Coaster) dài 2.400m từ đỉnh xuống chân thác. Tour canyoning (vượt thác) mạo hiểm rất phổ biến. Thác nhiều tầng, nước chảy quanh năm giữa rừng xanh.",["Trượt máng Alpine Coaster cực vui","Thử canyoning nếu thích mạo hiểm","Mang áo mưa vì hơi nước"],"Đường Prenn, Phường 3, Đà Lạt",11.9100,108.4483,"7:00–17:00","50.000đ (trượt máng: 100.000đ)","Quanh năm",["thác","trượt-máng","mạo-hiểm","rừng"],false,5),
// BÌNH THUẬN (4)
d("doi-cat-mui-ne","Đồi cát Mũi Né","Đồi cát bay Mũi Né","binh-thuan","thien-nhien","Cảnh quan sa mạc mini với đồi cát vàng – đỏ, đẹp nhất lúc bình minh.","Mũi Né có 2 đồi cát nổi tiếng: đồi cát đỏ (Red Sand Dunes) gần trung tâm và đồi cát trắng (White Sand Dunes) cách 30km. Cát uốn lượn như sa mạc Sahara thu nhỏ. Đẹp nhất lúc bình minh và hoàng hôn. Trượt cát và đi xe địa hình là hoạt động phổ biến.",["Đến bình minh hoặc hoàng hôn","Trượt cát tại đồi cát đỏ","Thuê xe jeep đến đồi cát trắng"],"Mũi Né, Phan Thiết, Bình Thuận",10.9533,108.2883,"Luôn mở cửa","Miễn phí (thuê xe: 150.000đ)","Bình minh / Hoàng hôn",["đồi-cát","sa-mạc","bình-minh","trượt-cát"],false,1),
d("bau-trang","Bàu Trắng","Bàu Trắng (White Lake)","binh-thuan","thien-nhien","Hồ nước ngọt giữa đồi cát, ốc đảo sa mạc đẹp như Sahara.","Bàu Trắng là hồ nước ngọt nằm giữa đồi cát trắng, cách Phan Thiết 30km. Cảnh quan như ốc đảo giữa sa mạc, nước hồ trong xanh phản chiếu trời mây. Xung quanh là đồi cát trắng mênh mông. Buổi sáng sớm, mặt hồ phẳng lặng như gương. Có thể thuê xe jeep từ Mũi Né.",["Kết hợp đồi cát trắng gần đó","Đến sáng sớm ngắm bàu yên tĩnh","Thuê xe jeep từ Mũi Né"],"Hoà Thắng, Bắc Bình, Bình Thuận",11.0583,108.3400,"Luôn mở cửa","10.000đ","Sáng sớm",["hồ","đồi-cát","ốc-đảo","thiên-nhiên"],false,2),
d("thap-cham-poshanu","Tháp Chàm Poshanu","Tháp Chàm Poshanu","binh-thuan","lich-su","Cụm tháp Chăm cổ trên đồi nhìn ra biển Phan Thiết.","Tháp Poshanu (Phố Hải) xây từ thế kỷ 8–9, gồm 3 tháp trên đồi Bà Nài nhìn ra biển. Kiến trúc gạch Chăm Pa đặc trưng. Nơi đây thờ thần Shiva. Lễ hội Katê của người Chăm diễn ra hàng năm rất đặc sắc. View biển từ đồi tháp rất đẹp.",["Đến vào lễ hội Katê","Chụp ảnh tháp với nền biển","Tham quan khoảng 30 phút"],"Phú Hài, Phan Thiết, Bình Thuận",10.9250,108.1483,"7:00–17:00","15.000đ","Quanh năm",["tháp-chàm","lịch-sử","chăm-pa","biển"],false,3),
d("ke-ga","Hải đăng Kê Gà","Hải đăng Kê Gà","binh-thuan","lich-su","Ngọn hải đăng cổ nhất Đông Nam Á (1899) trên hòn đảo nhỏ ngoài khơi.","Hải đăng Kê Gà xây năm 1897–1899, cao 35m trên đảo đá nhỏ ngoài khơi La Gi. Là ngọn hải đăng cổ nhất và cao nhất Đông Nam Á. Leo 183 bậc thang xoắn ốc lên đỉnh ngắm toàn cảnh biển. Đi thuyền thúng từ bờ ra đảo khoảng 10 phút. Cảnh hoàng hôn tại Kê Gà tuyệt đẹp.",["Đi thuyền thúng ra đảo","Leo 183 bậc lên đỉnh hải đăng","Ngắm hoàng hôn từ đảo"],"Tân Thành, Hàm Thuận Nam, Bình Thuận",10.6917,107.9850,"7:00–17:00","Thuyền: 30.000đ","Hoàng hôn",["hải-đăng","đảo","cổ","hoàng-hôn"],false,4),
];

const op=path.join(__dirname,'../src/data/destinations-trung-1.json');
fs.writeFileSync(op,JSON.stringify(dests,null,2),'utf-8');
console.log(`Generated ${dests.length} Miền Trung (part 1) destinations`);
