const fs=require('fs'),path=require('path');
let imgC=4000;
function img(){imgC++;return`https://images.unsplash.com/photo-160059654${imgC}-${imgC}ab${imgC}cd?w=800&h=600&fit=crop&auto=format`;}
function d(s,n,nv,p,c,desc,ld,tips,addr,lat,lng,h,f,bt,tags,ft,o){
return{id:s,slug:s,name:n,nameVi:nv,provinceSlug:p,category:c,description:desc,longDescription:ld,
images:[{src:img(),alt:n,caption:`${n} – cảnh đẹp`},{src:img(),alt:`${n} view`,caption:`Khung cảnh tại ${n}`}],
tips,address:addr,coordinates:{lat,lng},openingHours:h,entryFee:f,bestTimeToVisit:bt,tags,featured:ft,order:o};}

const dests=[
// TP.HCM (7)
d("nha-tho-duc-ba","Nhà Thờ Đức Bà","Nhà Thờ Chính Toà Đức Bà Sài Gòn","ho-chi-minh","lich-su","Công trình kiến trúc Pháp tiêu biểu, biểu tượng TP.HCM từ năm 1880.","Nhà thờ Đức Bà xây 1877–1880 theo phong cách Roman pha Gothic. Hai tháp chuông cao 58m, mặt tiền gạch đỏ từ Marseille. Toạ lạc công trường Paris, bên cạnh Bưu điện Trung tâm. Phía trước có tượng Đức Mẹ Hoà Bình.",["Đang trùng tu, ngắm từ bên ngoài","Kết hợp Bưu điện bên cạnh","Chụp ảnh sáng sớm"],"01 Công xã Paris, Quận 1, TP.HCM",10.7798,106.6990,"8:00–17:00","Miễn phí","Sáng sớm",["nhà-thờ","kiến-trúc-pháp","biểu-tượng"],true,1),
d("cho-ben-thanh","Chợ Bến Thành","Chợ Bến Thành","ho-chi-minh","van-hoa","Khu chợ lịch sử hơn 100 tuổi, trung tâm mua sắm ẩm thực Sài Gòn.","Chợ Bến Thành xây đầu thế kỷ 20, hàng nghìn gian hàng bán đủ loại. Ban đêm chuyển thành phố ẩm thực ngoài trời. Biểu tượng văn hoá Sài Gòn. Tháp đồng hồ mặt tiền là hình ảnh kinh điển.",["Trả giá khi mua hàng (giảm 30–50%)","Chợ đêm ẩm thực rất hay","Đến sáng sớm tránh đông"],"Lê Lợi, Quận 1, TP.HCM",10.7725,106.6980,"6:00–18:00 (ngày), 18–23h (đêm)","Miễn phí","Sáng hoặc tối",["chợ","ẩm-thực","mua-sắm","văn-hoá"],false,2),
d("dia-dao-cu-chi","Địa Đạo Củ Chi","Địa Đạo Củ Chi","ho-chi-minh","lich-su","Hệ thống địa đạo dài 250km, chứng tích kháng chiến chống Mỹ.","Địa đạo Củ Chi dài hơn 250km, xây từ kháng chiến chống Pháp, mở rộng thời chống Mỹ. Nhiều tầng với phòng họp, bệnh xá, kho vũ khí. Du khách chui hầm, xem mô hình bẫy. 2 khu tham quan: Bến Đình và Bến Dược.",["Đi theo tour có HDV","Mặc thoải mái để chui hầm","Có 2 khu: Bến Đình và Bến Dược"],"Phú Hiệp, Củ Chi, TP.HCM",11.1417,106.4635,"7:00–17:00","110.000đ","Sáng sớm",["địa-đạo","lịch-sử","chiến-tranh"],false,3),
d("dinh-doc-lap","Dinh Độc Lập","Dinh Độc Lập (Dinh Thống Nhất)","ho-chi-minh","lich-su","Dinh thự Tổng thống VNCH, nơi xe tăng húc đổ cổng ngày 30/4/1975.","Dinh Độc Lập xây 1962–1966, kiến trúc hiện đại. Là nơi làm việc của Tổng thống VNCH. Ngày 30/4/1975, xe tăng húc đổ cổng dinh – kết thúc chiến tranh. Nay là bảo tàng với phòng làm việc, hầm ngầm nguyên bản.",["Tham quan hầm ngầm dưới dinh","Dành 1–2 giờ tham quan","Thuê audio guide"],"135 Nam Kỳ Khởi Nghĩa, Q.1, TP.HCM",10.7769,106.6952,"7:30–16:00","65.000đ","Sáng",["dinh-thự","lịch-sử","bảo-tàng","chiến-tranh"],false,4),
d("buu-dien-trung-tam","Bưu điện Trung tâm","Bưu điện Trung tâm Sài Gòn","ho-chi-minh","lich-su","Công trình kiến trúc Pháp tuyệt đẹp, vẫn hoạt động bưu chính sau 130 năm.","Bưu điện Trung tâm Sài Gòn xây 1886–1891 do Gustave Eiffel thiết kế. Kiến trúc Renaissance Pháp với mái vòm, cửa kính, bản đồ cổ trên tường. Vẫn hoạt động bưu chính. Bên trong có quầy lưu niệm, bưu thiếp. Nằm ngay cạnh Nhà thờ Đức Bà.",["Gửi bưu thiếp từ bưu điện lịch sử","Ngắm bản đồ cổ trên tường","Kết hợp thăm Nhà thờ Đức Bà"],"02 Công xã Paris, Q.1, TP.HCM",10.7797,106.6999,"7:00–19:00 (T2–T6)","Miễn phí","Sáng",["bưu-điện","kiến-trúc-pháp","lịch-sử"],false,5),
d("bao-tang-chung-tich-chien-tranh","Bảo tàng Chứng tích Chiến tranh","Bảo tàng Chứng tích Chiến tranh","ho-chi-minh","lich-su","Bảo tàng chiến tranh được ghé thăm nhiều nhất Việt Nam.","Bảo tàng Chứng tích Chiến tranh trưng bày hiện vật, hình ảnh về chiến tranh Việt Nam. Nhiều du khách quốc tế đánh giá là bảo tàng xúc động nhất. Trưng bày máy bay, xe tăng ngoài sân. Bên trong có ảnh nạn nhân chất độc da cam, vũ khí chiến tranh.",["Nội dung khá nặng nề, chuẩn bị tâm lý","Dành 2 giờ tham quan","Có thuyết minh tiếng Anh"],"28 Võ Văn Tần, Q.3, TP.HCM",10.7794,106.6921,"7:30–17:00","40.000đ","Quanh năm",["bảo-tàng","chiến-tranh","lịch-sử"],false,6),
d("pho-di-bo-nguyen-hue","Phố đi bộ Nguyễn Huệ","Phố đi bộ Nguyễn Huệ","ho-chi-minh","giai-tri","Phố đi bộ sôi động nhất Sài Gòn, trung tâm giải trí và sự kiện.","Phố đi bộ Nguyễn Huệ dài 670m, rộng 64m, trung tâm Q.1. Buổi tối sôi động với nghệ sĩ đường phố, sự kiện văn hoá. Toà nhà UBND TP.HCM kiến trúc Pháp đẹp ở đầu phố. Hai bên là toà nhà cao tầng hiện đại. Nhiều quán café, nhà hàng xung quanh.",["Dạo phố buổi tối mát mẻ","Xem nghệ sĩ đường phố biểu diễn","Uống café tại The Café Apartments"],"Nguyễn Huệ, Q.1, TP.HCM",10.7737,106.7033,"Luôn mở cửa","Miễn phí","Tối",["phố-đi-bộ","giải-trí","đêm","sôi-động"],false,7),
// BÀ RỊA – VŨNG TÀU (4)
d("bai-truoc","Bãi Trước","Bãi Trước Vũng Tàu","ba-ria-vung-tau","thien-nhien","Bãi biển trung tâm thành phố với nhiều quán café view biển.","Bãi Trước nằm ngay trung tâm TP. Vũng Tàu, bờ cát ngắn hình bán nguyệt. Dọc bờ biển có công viên, quán café, nhà hàng hải sản view biển. Phù hợp dạo chơi, ngắm biển hơn là tắm. Gần các điểm tham quan trung tâm.",["Café ven biển buổi chiều","Ngắm hoàng hôn đẹp","Kết hợp dạo công viên ven biển"],"Bãi Trước, TP. Vũng Tàu",10.3467,107.0733,"Luôn mở cửa","Miễn phí","Chiều hoàng hôn",["biển","café","hoàng-hôn","trung-tâm"],true,1),
d("bai-sau","Bãi Sau","Bãi Sau (Thuỳ Vân)","ba-ria-vung-tau","thien-nhien","Bãi biển chính của Vũng Tàu, dài và sạch, phù hợp tắm biển.","Bãi Sau (Bãi Thuỳ Vân) dài 10km, cát mịn, sóng vừa phải. Là bãi tắm chính của Vũng Tàu. Dọc bãi có khách sạn, resort, nhà hàng hải sản. Cuối tuần đông du khách từ Sài Gòn. Khu vực phía nam yên tĩnh hơn.",["Cuối tuần rất đông từ Sài Gòn","Khu phía nam yên tĩnh hơn","Hải sản ven biển tươi ngon"],"Bãi Sau, TP. Vũng Tàu",10.3367,107.0917,"Luôn mở cửa","Miễn phí","Tháng 5–10",["biển","cát","tắm-biển","hải-sản"],false,2),
d("tuong-chua-kito","Tượng Chúa Kitô","Tượng Chúa Kitô Vua","ba-ria-vung-tau","tam-linh","Tượng Chúa cao 32m trên núi Nhỏ, một trong những tượng lớn nhất thế giới.","Tượng Chúa Kitô Vua xây 1971–1993, cao 32m, hai tay giang rộng 18,3m trên đỉnh núi Nhỏ. Là một trong những tượng Chúa lớn nhất thế giới. Leo 811 bậc thang lên đỉnh hoặc vào bên trong tượng. Từ trên ngắm toàn cảnh Vũng Tàu và biển.",["Leo 811 bậc, cần sức khoẻ","Vào bên trong tượng ngắm view","Đến sáng sớm tránh nóng"],"Núi Nhỏ, TP. Vũng Tàu",10.3283,107.0850,"6:30–17:00","Miễn phí","Sáng sớm",["tượng","tâm-linh","núi","view"],false,3),
d("ho-tram","Hồ Tràm","Bãi biển Hồ Tràm","ba-ria-vung-tau","thien-nhien","Vùng bãi biển hoang sơ với resort cao cấp, lý tưởng nghỉ dưỡng.","Hồ Tràm cách TP.HCM 120km, là vùng bãi biển còn hoang sơ. Cát trắng mịn, nước trong, ít đông đúc. Nhiều resort cao cấp: The Grand Ho Tram Strip, Melia. Rừng nguyên sinh ven biển. Phù hợp nghỉ dưỡng cuối tuần từ Sài Gòn.",["Đặt resort sớm vào cuối tuần","Tắm biển ít sóng hơn Vũng Tàu","Yên tĩnh hơn Vũng Tàu nhiều"],"Xuyên Mộc, Bà Rịa - Vũng Tàu",10.4667,107.3833,"Luôn mở cửa","Resort từ 2 triệu/đêm","Tháng 11–4",["biển","resort","hoang-sơ","nghỉ-dưỡng"],false,4),
// KIÊN GIANG (5)
d("dao-phu-quoc","Đảo Phú Quốc","Đảo Phú Quốc","kien-giang","thien-nhien","Đảo ngọc lớn nhất Việt Nam với bãi biển tuyệt đẹp và nước mắm nổi tiếng.","Phú Quốc là đảo lớn nhất VN (574km²), thiên đường biển đảo. Bãi Dài, Bãi Sao cát trắng nước trong. Hệ thống resort, khu vui chơi phát triển. Nước mắm Phú Quốc và tiêu Phú Quốc là đặc sản nổi tiếng. Hoàng hôn Phú Quốc đẹp bậc nhất VN.",["Thuê xe máy khám phá đảo","Ngắm hoàng hôn tại Bãi Dài","Mua nước mắm và tiêu làm quà"],"Phú Quốc, Kiên Giang",10.2290,103.9631,"Luôn mở cửa","Miễn phí","Tháng 11–4",["đảo","biển","hoàng-hôn","nước-mắm"],true,1),
d("bai-sao-phu-quoc","Bãi Sao","Bãi Sao Phú Quốc","kien-giang","thien-nhien","Bãi biển đẹp nhất Phú Quốc với cát trắng mịn và nước biển xanh ngọc.","Bãi Sao nằm phía Đông Nam Phú Quốc, được coi là bãi biển đẹp nhất đảo. Cát trắng mịn như kem, nước trong xanh ngọc bích. Sóng nhẹ, nước nông, phù hợp gia đình. Có nhà hàng, quán bar ven biển. Khung cảnh bình yên như thiên đường.",["Đến sáng sớm ít đông","Thuê phao và ghế bãi biển","Ăn hải sản nướng tại quán ven biển"],"An Thới, Phú Quốc, Kiên Giang",10.0567,104.0233,"Luôn mở cửa","Miễn phí","Tháng 11–4",["biển","cát-trắng","ngọc-bích","gia-đình"],false,2),
d("dinh-cau","Dinh Cậu","Dinh Cậu","kien-giang","tam-linh","Đền thờ cá Ông linh thiêng trên mỏm đá nhìn ra biển, biểu tượng Phú Quốc.","Dinh Cậu nằm trên mỏm đá bên cửa sông Dương Đông, thờ cá Ông (cá Voi) – vị thần bảo hộ ngư dân. Là nơi ngư dân cầu bình an trước khi ra khơi. Ngọn hải đăng nhỏ trên đỉnh. Là điểm ngắm hoàng hôn đẹp nhất thị trấn Dương Đông.",["Ngắm hoàng hôn tuyệt đẹp","Dạo chợ đêm Phú Quốc gần đó","Tham quan nhanh 15–20 phút"],"Dương Đông, Phú Quốc, Kiên Giang",10.2167,103.9583,"Luôn mở cửa","Miễn phí","Hoàng hôn",["đền","biển","hoàng-hôn","linh-thiêng"],false,3),
d("lang-chai-ham-ninh","Làng chài Hàm Ninh","Làng chài Hàm Ninh","kien-giang","van-hoa","Làng chài cổ với ghẹ Hàm Ninh nổi tiếng, trải nghiệm cuộc sống ngư dân.","Làng chài Hàm Ninh nằm phía Đông Phú Quốc, là làng chài lâu đời nhất đảo. Nổi tiếng với ghẹ luộc Hàm Ninh – thương hiệu ẩm thực Phú Quốc. Bến cầu tàu gỗ dài ra biển, view đẹp. Du khách trải nghiệm mua hải sản tươi sống, ăn ngay tại chỗ.",["Ăn ghẹ luộc – đặc sản nổi tiếng","Mua hải sản tươi sống","Chụp ảnh tại cầu tàu gỗ"],"Hàm Ninh, Phú Quốc, Kiên Giang",10.1833,104.0667,"Luôn mở cửa","Miễn phí (ăn: 200–500k)","Sáng hoặc chiều",["làng-chài","hải-sản","ghẹ","văn-hoá"],false,4),
d("vuon-quoc-gia-phu-quoc","VQG Phú Quốc","Vườn Quốc gia Phú Quốc","kien-giang","thien-nhien","Rừng nguyên sinh chiếm 70% diện tích đảo với hệ sinh thái đa dạng.","VQG Phú Quốc chiếm 31.422ha (gần 70% đảo), rừng nguyên sinh bao phủ dãy núi xương sống đảo. Nhiều loài quý: voọc bạc, kỳ đà, chim quý. Suối Tranh, suối Đá Bàn là điểm trekking đẹp. Rừng sâm Phú Quốc quý hiếm. Du khách trekking, ngắm chim, tắm suối.",["Trekking suối Tranh đẹp","Mang giày trekking và thuốc muỗi","Thuê hướng dẫn viên rừng"],"Phú Quốc, Kiên Giang",10.3500,104.0000,"6:00–17:00","40.000đ","Tháng 11–4",["rừng","trekking","suối","bảo-tồn"],false,5),
// CẦN THƠ (4)
d("cho-noi-cai-rang","Chợ nổi Cái Răng","Chợ nổi Cái Răng","can-tho","van-hoa","Chợ nổi lớn nhất và nổi tiếng nhất đồng bằng sông Cửu Long.","Chợ nổi Cái Răng họp trên sông Cần Thơ từ sáng sớm. Hàng trăm ghe xuồng mua bán trái cây, nông sản. Mỗi ghe treo sản phẩm bán lên cây sào (bẹo). Du khách đi ghe ngắm cảnh, mua trái cây tươi, ăn phở, hủ tiếu trên sông.",["Đi từ 5–6h sáng để đúng giờ chợ họp","Thuê ghe từ bến Ninh Kiều","Thử hủ tiếu và cà phê trên sông"],"Cái Răng, Cần Thơ",10.0167,105.7500,"5:00–9:00 sáng","Thuê ghe: 100.000–200.000đ","Sáng sớm (5–7h)",["chợ-nổi","sông","trái-cây","miền-tây"],true,1),
d("ben-ninh-kieu","Bến Ninh Kiều","Bến Ninh Kiều","can-tho","van-hoa","Bến sông lung linh về đêm, trung tâm du lịch Cần Thơ.","Bến Ninh Kiều nằm bên bờ sông Hậu, trung tâm TP. Cần Thơ. Buổi tối lung linh đèn màu, nhiều nhà hàng, quán café ven sông. Chợ đêm bán đặc sản miền Tây. Bến xuất phát đi chợ nổi Cái Răng. Tượng Bác Hồ và công viên ven sông.",["Dạo bến tối ngắm đèn","Xuất phát đi chợ nổi từ đây","Ăn chợ đêm Ninh Kiều"],"Bến Ninh Kiều, Ninh Kiều, Cần Thơ",10.0333,105.7833,"Luôn mở cửa","Miễn phí","Tối",["bến-sông","đêm","chợ-đêm","ven-sông"],false,2),
d("vuon-co-bang-lang","Vườn cò Bằng Lăng","Vườn cò Bằng Lăng","can-tho","thien-nhien","Khu sinh thái với hàng vạn con cò trú ngụ trên vườn cây.","Vườn cò Bằng Lăng ở Thốt Nốt, rộng 1,3ha, nơi trú ngụ của hàng vạn con cò. Chiều muộn cò bay về tổ, cảnh tượng ngoạn mục. Nhiều loài cò: cò trắng, cò bợ, cò ngàng. Khu vực yên bình giữa đồng ruộng.",["Đến chiều 16–17h xem cò bay về","Mang ống nhòm và tele","Giữ yên lặng"],"Thốt Nốt, Cần Thơ",10.2667,105.5333,"15:00–18:00","20.000đ","Chiều muộn",["cò","chim","sinh-thái","đồng-quê"],false,3),
d("chua-ong-can-tho","Chùa Ông","Chùa Ông Cần Thơ","can-tho","tam-linh","Ngôi chùa Hoa cổ nhất Cần Thơ với kiến trúc lộng lẫy bên bến Ninh Kiều.","Chùa Ông (Quảng Triệu Hội Quán) xây 1894 bởi cộng đồng người Hoa, thờ Quan Công. Kiến trúc Hoa truyền thống lộng lẫy với đèn lồng, phù điêu. Nằm ngay bên bến Ninh Kiều, dễ kết hợp tham quan. Là di tích lịch sử cấp quốc gia.",["Kết hợp dạo bến Ninh Kiều","Chiêm ngưỡng kiến trúc Hoa","Thắp nhang cầu phúc"],"26 Hai Bà Trưng, Ninh Kiều, Cần Thơ",10.0350,105.7817,"6:00–18:00","Miễn phí","Quanh năm",["chùa","kiến-trúc-hoa","tâm-linh","di-tích"],false,4),
// BÌNH DƯƠNG (3)
d("dai-nam","Đại Nam Văn Hiến","Khu du lịch Đại Nam","binh-duong","giai-tri","Quần thể giải trí lớn nhất miền Nam với sở thú, khu vui chơi và biển nhân tạo.","Đại Nam rộng 450ha, gồm khu vui chơi, sở thú Safari World, biển nhân tạo, đền thờ và khu mua sắm. Lớn nhất miền Nam. Nhiều trò chơi cảm giác mạnh. Biển nhân tạo dài 400m. Phù hợp gia đình có trẻ em.",["Dành cả ngày tham quan","Mang kem chống nắng","Đi ngày thường ít đông"],"Hiệp An, Thủ Dầu Một, Bình Dương",11.0167,106.6333,"8:00–17:00","200.000đ","Quanh năm",["giải-trí","sở-thú","biển","gia-đình"],false,1),
d("nui-chau-thoi","Núi Châu Thới","Núi Châu Thới","binh-duong","tam-linh","Ngọn núi nhỏ với chùa cổ trên đỉnh, điểm tâm linh quan trọng Bình Dương.","Núi Châu Thới cao 82m, trên đỉnh có chùa Châu Thới xây từ 1681. Là ngọn núi duy nhất giữa đồng bằng Bình Dương. Leo 220 bậc thang lên chùa. Từ đỉnh ngắm toàn cảnh thành phố. Chùa cổ kính, tượng Phật lớn.",["Leo 220 bậc thang","Ngắm toàn cảnh từ đỉnh núi","Mặc trang phục kín đáo"],"Bình An, Dĩ An, Bình Dương",10.9000,106.7167,"5:00–18:00","Miễn phí","Sáng sớm",["núi","chùa","tâm-linh","view"],false,2),
d("khu-du-lich-lai-thieu","Vườn trái cây Lái Thiêu","Vườn trái cây Lái Thiêu","binh-duong","thien-nhien","Vùng vườn trái cây nổi tiếng với măng cụt, sầu riêng, chôm chôm mùa hè.","Lái Thiêu (Thuận An) nổi tiếng với vườn trái cây mùa hè. Măng cụt, sầu riêng, chôm chôm, bòn bon chín rộ tháng 5–7. Du khách vào vườn hái và ăn thoải mái. Không gian xanh mát giữa thành phố. Nhiều nhà vườn mở cửa đón khách.",["Đến tháng 5–7 mùa trái cây","Mua vé vào vườn ăn thoả thích","Mang theo nước uống"],"Lái Thiêu, Thuận An, Bình Dương",10.9167,106.6667,"7:00–17:00","50.000–100.000đ","Tháng 5–7",["trái-cây","vườn","mùa-hè","sinh-thái"],false,3),
// BÌNH PHƯỚC (3)
d("vuon-quoc-gia-bu-gia-map","VQG Bù Gia Mập","Vườn Quốc gia Bù Gia Mập","binh-phuoc","thien-nhien","Khu rừng nguyên sinh lớn với đa dạng linh trưởng quý hiếm.","VQG Bù Gia Mập rộng 26.032ha, rừng nguyên sinh đa dạng sinh học cao. Nhiều loài linh trưởng quý: voọc chà vá chân đen, vượn đen má vàng. Suối và thác nước tự nhiên đẹp. Du khách trekking, nghiên cứu, ngắm chim và thú.",["Thuê HDV bản địa","Mang đồ trekking đầy đủ","Cơ hội ngắm voọc vào sáng sớm"],"Bù Gia Mập, Bình Phước",12.1000,107.1833,"Luôn mở cửa","40.000đ","Tháng 11–4",["rừng","linh-trưởng","trekking","bảo-tồn"],false,1),
d("nui-ba-ra","Núi Bà Rá","Núi Bà Rá","binh-phuoc","thien-nhien","Ngọn núi cao nhất tỉnh (723m) với chùa và cảnh quan đẹp.","Núi Bà Rá cao 723m, cao nhất Bình Phước. Đường lên đỉnh qua rừng cây và bậc thang. Trên đỉnh có chùa và đài quan sát ngắm toàn cảnh. Di tích lịch sử kháng chiến trên núi. Không khí mát mẻ, trong lành.",["Leo núi sáng sớm","Mang nước và giày thoải mái","Ngắm toàn cảnh từ đỉnh"],"Phước Long, Bình Phước",11.8500,107.0000,"Luôn mở cửa","Miễn phí","Sáng sớm",["núi","chùa","trekking","view"],false,2),
d("ho-suoi-cam","Hồ Suối Cam","Hồ Suối Cam","binh-phuoc","thien-nhien","Hồ nước trong lành giữa đồi thông, điểm sinh thái yên bình.","Hồ Suối Cam nằm trong TP. Đồng Xoài, nước xanh trong giữa đồi thông. Là điểm du lịch sinh thái, picnic cuối tuần của người dân địa phương. Có nhà hàng, quán café ven hồ. Không gian yên tĩnh, mát mẻ.",["Picnic ven hồ cuối tuần","Café view hồ","Câu cá trên hồ"],"Đồng Xoài, Bình Phước",11.5333,106.8667,"Luôn mở cửa","Miễn phí","Quanh năm",["hồ","thông","sinh-thái","yên-bình"],false,3),
// ĐỒNG NAI (3)
d("vuon-quoc-gia-cat-tien","VQG Cát Tiên","Vườn Quốc gia Cát Tiên","dong-nai","thien-nhien","Khu dự trữ sinh quyển thế giới với rừng nguyên sinh lớn nhất Nam Bộ.","VQG Cát Tiên là Khu dự trữ Sinh quyển UNESCO, rộng 71.920ha. Rừng nguyên sinh đa dạng: gấu, bò tót, voi. Vùng đất ngập nước Bàu Sấu – nơi cá sấu hoang dã sinh sống. Trekking đêm ngắm thú quý. Du khách ở nhà khách trong VQG.",["Trekking đêm ngắm thú","Thăm Bàu Sấu xem cá sấu","Ở nhà khách VQG qua đêm"],"Tân Phú, Đồng Nai",11.4333,107.4333,"6:00–17:00","60.000đ","Tháng 11–4",["rừng","sinh-quyển","trekking","cá-sấu"],false,1),
d("khu-du-lich-buu-long","KDL Bửu Long","Khu du lịch Bửu Long","dong-nai","thien-nhien","Cảnh quan núi đá kỳ vĩ soi bóng xuống hồ, \"Hạ Long thu nhỏ\" phía Nam.","Bửu Long nằm tại Biên Hoà, nổi tiếng với núi đá kỳ vĩ soi bóng xuống hồ nước xanh ngọc. Được ví \"Hạ Long thu nhỏ\" của miền Nam. Chùa Bửu Long kiến trúc Khmer ấn tượng trên đỉnh núi. Nhiều hang động và bậc thang leo núi.",["Chụp ảnh phản chiếu núi đá","Thăm chùa Bửu Long trên đỉnh","Kết hợp dạo quanh hồ"],"Bửu Long, Biên Hoà, Đồng Nai",10.9500,106.8333,"6:00–18:00","15.000đ","Sáng sớm",["núi-đá","hồ","chùa","phản-chiếu"],false,2),
d("thac-mai","Thác Mai","Thác Mai","dong-nai","thien-nhien","Thác nước hoang sơ trong VQG Cát Tiên, đẹp giữa rừng nguyên sinh.","Thác Mai nằm trong VQG Cát Tiên, nước đổ qua nhiều tầng đá giữa rừng nguyên sinh. Đường đi qua rừng cây cổ thụ rất đẹp. Hồ nước dưới thác trong veo. Tắm thác mát mẻ trong mùa khô. Hoang sơ, ít du khách.",["Đi từ trung tâm VQG mất 2 giờ","Mang dép chống trơn","Tắm thác mùa khô an toàn"],"VQG Cát Tiên, Tân Phú, Đồng Nai",11.4500,107.4000,"7:00–16:00","Gồm vé VQG","Tháng 12–4",["thác","rừng","hoang-sơ","tắm-thác"],false,3),
// TÂY NINH (3)
d("nui-ba-den","Núi Bà Đen","Núi Bà Đen","tay-ninh","tam-linh","\"Nóc nhà Nam Bộ\" cao 986m với cáp treo hiện đại và chùa linh thiêng.","Núi Bà Đen cao 986m, cao nhất Nam Bộ. Cáp treo Sun World dài 1.677m đưa lên gần đỉnh. Chùa Bà Đen linh thiêng, hàng triệu người hành hương mỗi năm. Trên đỉnh có tượng Phật Bà cao 72m. Buổi sáng biển mây phủ quanh núi rất đẹp.",["Đi cáp treo tiết kiệm sức","Đến sáng sớm ngắm biển mây","Mặc trang phục kín đáo vào chùa"],"TX. Hoà Thành, Tây Ninh",11.3500,106.1667,"5:00–18:00","Cáp treo: 200.000đ","Sáng sớm (biển mây)",["núi","cáp-treo","chùa","biển-mây"],false,1),
d("toa-thanh-cao-dai","Toà Thánh Cao Đài","Toà Thánh Cao Đài Tây Ninh","tay-ninh","tam-linh","Trung tâm đạo Cao Đài với kiến trúc rực rỡ Đông – Tây.","Toà Thánh Cao Đài xây 1933–1955, trung tâm tôn giáo Cao Đài. Kiến trúc rực rỡ kết hợp phong cách nhà thờ, chùa chiền và thánh đường Hồi giáo. Lễ cầu nguyện 4 lần/ngày (6h, 12h, 18h, 24h). Du khách được dự lễ và ngắm kiến trúc từ tầng trên.",["Dự lễ cầu nguyện lúc 12h","Mặc trang phục trang nghiêm","Không chụp ảnh flash"],"Long Hoà, Hoà Thành, Tây Ninh",11.2917,106.1583,"Theo giờ lễ","Miễn phí","Lễ trưa 12h",["tôn-giáo","cao-đài","kiến-trúc","rực-rỡ"],false,2),
d("ho-dau-tieng","Hồ Dầu Tiếng","Hồ Dầu Tiếng","tay-ninh","thien-nhien","Hồ nhân tạo lớn nhất Việt Nam, cảnh quan sơn thuỷ thanh bình.","Hồ Dầu Tiếng rộng 27.000ha, hồ nhân tạo lớn nhất VN. Mặt hồ phẳng lặng bao quanh bởi rừng cao su và đồi xanh. Du khách câu cá, chèo thuyền, picnic ven hồ. Hoàng hôn trên hồ tuyệt đẹp.",["Câu cá thư giãn","Ngắm hoàng hôn trên hồ","Mang đồ picnic"],"Dầu Tiếng, Tây Ninh",11.3500,106.3667,"Luôn mở cửa","Miễn phí","Chiều hoàng hôn",["hồ","câu-cá","hoàng-hôn","yên-bình"],false,3),
// LONG AN (3)
d("lang-noi-tan-lap","Làng nổi Tân Lập","Làng nổi Tân Lập","long-an","thien-nhien","Rừng tràm xanh mướt với con đường xuyên rừng trên mặt nước.","Làng nổi Tân Lập nổi tiếng với rừng tràm nguyên sinh xanh mướt. Du khách chèo xuồng xuyên tán rừng tràm trên mặt nước yên bình. Cầu đi bộ xuyên rừng dài 5km. Mùa nước nổi đẹp nhất. Hệ sinh thái đất ngập nước phong phú.",["Chèo xuồng qua rừng tràm","Đi cầu đi bộ xuyên rừng","Mùa nước nổi (T8–11) đẹp nhất"],"Tân Lập, Mộc Hoá, Long An",10.6833,106.0833,"7:00–17:00","100.000đ","Tháng 8–11",["rừng-tràm","xuồng","sinh-thái","đất-ngập-nước"],false,1),
d("khu-di-tich-binh-ta","Khu di tích Bình Tả","Khu di tích khảo cổ Bình Tả","long-an","lich-su","Di chỉ khảo cổ văn hoá Óc Eo cổ đại.","Khu di tích Bình Tả thuộc Đức Hoà, là di chỉ khảo cổ văn hoá Óc Eo (thế kỷ 1–7 SCN). Nhiều hiện vật: gạch cổ, tượng đá, đồ gốm của nền văn minh Phù Nam. Gò tháp Bình Tả có nền gạch cổ nguyên vẹn. Giá trị nghiên cứu lịch sử quan trọng.",["Kết hợp hướng dẫn viên","Tham quan khoảng 1 giờ","Không gian yên tĩnh"],"Đức Hoà, Long An",10.9167,106.4333,"7:00–17:00","Miễn phí","Quanh năm",["khảo-cổ","óc-eo","lịch-sử","di-chỉ"],false,2),
d("khu-du-lich-cong-troi","KDL Cộng Trời","KDL sinh thái Cộng Trời","long-an","thien-nhien","Đồng sen bát ngát và rừng tràm, điểm sinh thái yên bình.","KDL Cộng Trời nổi tiếng với đồng sen bát ngát mùa hè. Rừng tràm xanh mát, kênh rạch chằng chịt. Du khách chèo xuồng, hái sen, thưởng thức ẩm thực đồng quê. Gần khu di tích Bình Tả.",["Mùa sen tháng 5–7 đẹp nhất","Thử gỏi ngó sen","Chèo xuồng giữa đồng sen"],"Đức Hoà, Long An",10.9000,106.4500,"7:00–17:00","50.000đ","Tháng 5–7 (sen)",["sen","rừng-tràm","đồng-quê","xuồng"],false,3),
// TIỀN GIANG (3)
d("cu-lao-thoi-son","Cù lao Thới Sơn","Cù lao Thới Sơn","tien-giang","van-hoa","Đảo giữa sông Tiền, trải nghiệm sông nước và đờn ca tài tử.","Cù lao Thới Sơn là đảo giữa sông Tiền, điểm du lịch sinh thái nổi tiếng nhất Tiền Giang. Du khách đi xuồng ba lá trên kênh rạch, nghe đờn ca tài tử, thưởng thức mật ong, trái cây. Vườn cây ăn trái xum xuê. Trải nghiệm cuộc sống miệt vườn miền Tây.",["Đi xuồng ba lá trên kênh rạch","Nghe đờn ca tài tử","Ăn trái cây miền Tây tại vườn"],"Thới Sơn, Châu Thành, Tiền Giang",10.3333,106.5333,"7:00–17:00","Tour: 150.000đ","Quanh năm",["cù-lao","sông-nước","đờn-ca","trái-cây"],false,1),
d("chua-vinh-trang","Chùa Vĩnh Tràng","Chùa Vĩnh Tràng","tien-giang","tam-linh","Ngôi chùa kiến trúc Đông – Tây độc đáo nhất miền Tây Nam Bộ.","Chùa Vĩnh Tràng xây đầu thế kỷ 19, kiến trúc pha trộn Việt – Hoa – Khmer – Pháp độc đáo. Mặt tiền phong cách Pháp, bên trong trang trí Á Đông. Tượng Phật nhập Niết bàn dài 12m. Vườn kiểng cổ thụ đẹp. Là di tích quốc gia.",["Chiêm ngưỡng kiến trúc pha trộn","Xem tượng Phật nhập Niết bàn","Dạo vườn kiểng cổ thụ"],"Mỹ Phong, TP. Mỹ Tho, Tiền Giang",10.3467,106.3517,"6:00–18:00","Miễn phí","Quanh năm",["chùa","kiến-trúc","tâm-linh","vườn-kiểng"],false,2),
d("trai-ran-dong-tam","Trại rắn Đồng Tâm","Trại rắn Đồng Tâm","tien-giang","giai-tri","Trung tâm nghiên cứu rắn lớn nhất Việt Nam với nhiều loài rắn độc.","Trại rắn Đồng Tâm thuộc Quân khu 9, là trung tâm nuôi và nghiên cứu rắn lớn nhất VN. Hơn 50 loài rắn gồm hổ mang chúa, rắn lục, trăn. Sản xuất huyết thanh chống nọc rắn. Du khách xem biểu diễn rắn, tìm hiểu về rắn và mua rượu rắn.",["Xem biểu diễn rắn vui","Không chạm vào rắn","Mua rượu rắn làm quà"],"Châu Thành, Tiền Giang",10.3167,106.3167,"7:00–17:00","30.000đ","Quanh năm",["rắn","nghiên-cứu","giáo-dục","giải-trí"],false,3),
// BẾN TRE (3)
d("con-phung","Cồn Phụng","Cồn Phụng","ben-tre","van-hoa","Cù lao trên sông Tiền với vườn dừa và xưởng kẹo dừa nổi tiếng.","Cồn Phụng nằm giữa sông Tiền, nổi tiếng với vườn dừa xanh mát. Du khách đi xuồng, thăm xưởng kẹo dừa, thưởng thức nhạc tài tử và trái cây miệt vườn. Đạo Dừa – tôn giáo đặc biệt từng hoạt động trên cù lao. Trải nghiệm sông nước điển hình miền Tây.",["Đi xuồng xuyên kênh rạch","Xem làm kẹo dừa","Uống nước dừa tươi"],"Tân Thạch, Châu Thành, Bến Tre",10.3000,106.4500,"7:00–17:00","100.000đ (gồm tour)","Quanh năm",["cù-lao","dừa","kẹo-dừa","sông-nước"],false,1),
d("vuon-dua-ben-tre","Vườn dừa Bến Tre","Vườn dừa Bến Tre","ben-tre","thien-nhien","Vùng dừa bạt ngàn nổi tiếng nhất Việt Nam, xứ sở kẹo dừa.","Bến Tre có hàng triệu cây dừa, được mệnh danh xứ Dừa. Vườn dừa rợp bóng mát, du khách đi thuyền xuyên kênh rạch dưới tán dừa, nghe nhạc tài tử, ăn trái cây. Nhiều sản phẩm từ dừa: kẹo, mứt, dầu, rượu. Trải nghiệm bình dị miệt vườn.",["Đi thuyền xuyên kênh rạch","Mua đặc sản dừa làm quà","Thử nhiều sản phẩm từ dừa"],"Bến Tre",10.2333,106.3667,"7:00–17:00","50.000đ","Quanh năm",["dừa","sông-nước","miệt-vườn","thuyền"],false,2),
d("san-chim-vam-ho","Sân chim Vàm Hồ","Sân chim Vàm Hồ","ben-tre","thien-nhien","Khu trú ngụ của hàng vạn con cò và chim nước giữa vườn dừa.","Sân chim Vàm Hồ rộng 49ha, nơi trú ngụ của hàng vạn con cò, vạc, chim nước. Chiều muộn cò bay về tổ ngoạn mục. Nằm giữa vườn dừa nước, kênh rạch. Du khách đi thuyền quanh sân chim ngắm cảnh. Hệ sinh thái đất ngập nước phong phú.",["Đến chiều 16–17h","Đi thuyền quanh sân chim","Giữ yên lặng"],"Ba Tri, Bến Tre",10.0667,106.6167,"15:00–18:00","30.000đ","Chiều muộn",["chim","cò","đất-ngập-nước","thuyền"],false,3),
// VĨNH LONG (3)
d("cu-lao-an-binh","Cù lao An Bình","Cù lao An Bình","vinh-long","van-hoa","Hòn đảo yên bình giữa sông Cổ Chiên với nhà cổ và vườn trái cây.","Cù lao An Bình nằm giữa sông Cổ Chiên, nổi tiếng với nhà cổ hàng trăm năm và vườn trái cây sum suê. Du khách đi phà qua sông, đạp xe trên đường làng, thăm nhà cổ, ăn cơm dân dã. Homestay ven sông yên bình. Trải nghiệm sông nước đích thực.",["Đạp xe quanh cù lao","Thăm nhà cổ cụ Hai","Ở homestay ven sông"],"An Bình, Long Hồ, Vĩnh Long",10.2333,105.9667,"Luôn mở cửa","Phà: 5.000đ","Quanh năm",["cù-lao","nhà-cổ","vườn","sông-nước"],false,1),
d("nha-co-vinh-long","Nhà cổ Vĩnh Long","Nhà cổ Vĩnh Long","vinh-long","van-hoa","Nhà cổ Nam Bộ hàng trăm năm tuổi với kiến trúc gỗ tinh xảo.","Vĩnh Long có nhiều ngôi nhà cổ Nam Bộ hàng trăm năm tuổi trên cù lao An Bình. Kiến trúc gỗ quý, chạm khắc tinh xảo, pha trộn Việt – Hoa. Nhà cổ cụ Hai Phước, nhà cổ ông Kỳ là điểm tham quan nổi bật. Chủ nhà niềm nở đón khách, kể chuyện xưa.",["Tham quan nhà cổ cụ Hai","Xem kiến trúc gỗ quý","Nghe chủ nhà kể chuyện"],"An Bình, Long Hồ, Vĩnh Long",10.2300,105.9700,"8:00–17:00","20.000đ","Quanh năm",["nhà-cổ","kiến-trúc","nam-bộ","gỗ-quý"],false,2),
d("vuon-trai-cay-vinh-long","Vườn trái cây Vĩnh Long","Vườn trái cây Vĩnh Long","vinh-long","thien-nhien","Vườn trái cây nhiệt đới 4 mùa với chôm chôm, măng cụt, sầu riêng.","Vĩnh Long có nhiều vườn trái cây nhiệt đới trên các cù lao. Quanh năm có trái cây: chôm chôm, măng cụt, sầu riêng, bưởi. Du khách vào vườn hái trái, ăn thoả thích. Nhiều vườn mở homestay kết hợp trải nghiệm nông nghiệp.",["Mùa trái cây chính: tháng 5–7","Vào vườn hái và ăn thoải mái","Mua trái cây tươi làm quà"],"Long Hồ, Vĩnh Long",10.2500,105.9500,"7:00–17:00","50.000đ","Tháng 5–7",["trái-cây","vườn","nhiệt-đới","nông-nghiệp"],false,3),
// TRÀ VINH (3)
d("chua-ang","Chùa Âng","Chùa Âng (Angkorajaborey)","tra-vinh","tam-linh","Ngôi chùa Khmer cổ hơn 1.000 năm với kiến trúc lộng lẫy.","Chùa Âng xây từ thế kỷ 10, là ngôi chùa Khmer cổ nhất Trà Vinh. Kiến trúc Khmer truyền thống với mái nhọn, phù điêu, tượng thần tinh xảo. Khuôn viên rộng với cây cổ thụ hàng trăm năm. Là trung tâm sinh hoạt cộng đồng Khmer địa phương.",["Mặc trang phục kín đáo","Chiêm ngưỡng kiến trúc Khmer","Kết hợp thăm Ao Bà Om gần đó"],"TP. Trà Vinh",9.9467,106.3417,"6:00–18:00","Miễn phí","Quanh năm",["chùa","khmer","cổ","kiến-trúc"],false,1),
d("ao-ba-om","Ao Bà Om","Ao Bà Om","tra-vinh","thien-nhien","Ao nước cổ hình chữ nhật bao quanh bởi hàng trăm cây sao cổ thụ.","Ao Bà Om có diện tích 3ha, hình chữ nhật đều đặn, gắn truyền thuyết cuộc thi đào ao giữa đàn ông và đàn bà. Bao quanh bởi hàng trăm cây sao cổ thụ hàng trăm năm tạo bóng mát. Không gian yên bình. Gần chùa Âng và Bảo tàng Văn hoá dân tộc Khmer.",["Dạo quanh ao dưới tán sao cổ thụ","Kết hợp thăm chùa Âng và bảo tàng","Đến sáng sớm yên tĩnh nhất"],"TP. Trà Vinh",9.9483,106.3383,"Luôn mở cửa","Miễn phí","Sáng sớm",["ao","cổ-thụ","truyền-thuyết","yên-bình"],false,2),
d("bien-ba-dong","Biển Ba Động","Biển Ba Động","tra-vinh","thien-nhien","Bãi biển hoang sơ với hàng phi lao xanh mát ven bờ.","Biển Ba Động nằm ở huyện Duyên Hải, bãi cát dài với hàng phi lao rì rào. Biển yên bình, ít du khách. Hải sản tươi ngon giá rẻ. Gần đó có rừng ngập mặn. Là điểm nghỉ mát của người dân Trà Vinh.",["Bãi biển vắng, yên bình","Hải sản rẻ và tươi","Đường đi hơi xa"],"Duyên Hải, Trà Vinh",9.6333,106.5167,"Luôn mở cửa","Miễn phí","Tháng 11–4",["biển","hoang-sơ","phi-lao","yên-tĩnh"],false,3),
// ĐỒNG THÁP (3)
d("vuon-quoc-gia-tram-chim","VQG Tràm Chim","Vườn Quốc gia Tràm Chim","dong-thap","thien-nhien","Nơi cư trú cuối cùng của sếu đầu đỏ quý hiếm tại Đông Nam Á.","VQG Tràm Chim rộng 7.313ha, đất ngập nước nổi tiếng với loài sếu đầu đỏ (Eastern Sarus Crane) quý hiếm. Mùa khô (tháng 12–5) sếu bay về đây. Rừng tràm ngập nước, sen hồng bạt ngát. Du khách đi thuyền ngắm chim, chụp ảnh thiên nhiên hoang dã.",["Mùa sếu: tháng 12–5","Đi thuyền ngắm chim sáng sớm","Mang ống nhòm và máy ảnh tele"],"Tam Nông, Đồng Tháp",10.7167,105.5333,"6:00–17:00","60.000đ (gồm thuyền)","Tháng 12–5 (sếu)",["sếu","chim","tràm","đất-ngập-nước"],false,1),
d("lang-hoa-sa-dec","Làng hoa Sa Đéc","Làng hoa Sa Đéc","dong-thap","van-hoa","Vựa hoa lớn nhất miền Nam với hàng trăm loài hoa rực rỡ quanh năm.","Làng hoa Sa Đéc là vùng trồng hoa lớn nhất miền Nam, cung cấp hoa cho cả nước. Hàng trăm loài hoa rực rỡ quanh năm, đặc biệt đẹp dịp Tết. Du khách dạo vườn hoa, chụp ảnh. Nhà cổ Huỳnh Thuỷ Lê – bối cảnh tiểu thuyết L'Amant của Marguerite Duras gần đó.",["Dịp Tết hoa đẹp nhất","Thăm nhà cổ Huỳnh Thuỷ Lê","Mua hoa kiểng làm quà"],"Sa Đéc, Đồng Tháp",10.3000,105.7667,"7:00–17:00","20.000đ","Tết Nguyên đán",["hoa","vườn","làng-nghề","tết"],false,2),
d("khu-di-tich-xeo-quit","Khu di tích Xẻo Quýt","Khu di tích Xẻo Quýt","dong-thap","lich-su","Căn cứ cách mạng giữa rừng tràm, nay là điểm du lịch sinh thái.","Xẻo Quýt là căn cứ Tỉnh uỷ Đồng Tháp trong kháng chiến, ẩn giữa rừng tràm ngập nước. Nay trở thành KDL sinh thái. Du khách chèo xuồng xuyên rừng tràm, thăm nhà hầm, ngắm chim cò. Mùa nước nổi (T8–11) đẹp nhất, sen nở hồng rực.",["Chèo xuồng qua rừng tràm","Mùa nước nổi đẹp nhất","Thăm di tích cách mạng"],"Cao Lãnh, Đồng Tháp",10.5167,105.6167,"7:00–17:00","30.000đ","Tháng 8–11",["rừng-tràm","căn-cứ","xuồng","sinh-thái"],false,3),
// AN GIANG (4)
d("nui-cam","Núi Cấm","Núi Cấm (Thiên Cấm Sơn)","an-giang","tam-linh","Đỉnh cao nhất đồng bằng sông Cửu Long với chùa chiền và cáp treo.","Núi Cấm cao 710m, cao nhất ĐBSCL, thuộc vùng Bảy Núi (Thất Sơn) huyền bí. Cáp treo lên gần đỉnh. Trên núi có nhiều chùa chiền, hồ nước, thác. Rừng cây xanh mát. Truyền thuyết về Bảy Núi huyền bí. Đặc sản: dâu Núi Cấm, đường thốt nốt.",["Đi cáp treo lên núi","Thăm chùa Phật Lớn","Ăn dâu Núi Cấm"],"Tịnh Biên, An Giang",10.5167,104.9833,"5:00–18:00","Cáp treo: 130.000đ","Quanh năm",["núi","cáp-treo","chùa","thất-sơn"],false,1),
d("nui-sam","Núi Sam","Núi Sam","an-giang","tam-linh","Núi linh thiêng nhất miền Nam với Miếu Bà Chúa Xứ nổi tiếng.","Núi Sam cao 284m, nổi tiếng với Miếu Bà Chúa Xứ – ngôi miếu linh thiêng nhất miền Nam, hàng triệu người hành hương mỗi năm. Trên núi có chùa Hang, lăng Thoại Ngọc Hầu, chùa Tây An kiến trúc Ấn Độ. Lễ vía Bà tháng 4 âm lịch rất lớn.",["Viếng Miếu Bà Chúa Xứ","Leo núi Sam ngắm cảnh","Lễ vía Bà tháng 4 rất đông"],"Châu Đốc, An Giang",10.6833,105.1167,"Luôn mở cửa","Miễn phí","Tháng 4 âm lịch (vía Bà)",["núi","miếu-bà","tâm-linh","hành-hương"],false,2),
d("lang-cham-chau-giang","Làng Chăm Châu Giang","Làng Chăm Châu Giang","an-giang","van-hoa","Làng người Chăm Islam giữ gìn văn hoá độc đáo bên sông Hậu.","Làng Chăm Châu Giang ở Châu Đốc, cộng đồng người Chăm theo đạo Islam sinh sống hàng trăm năm. Thánh đường Hồi giáo, nhà sàn ven sông, trang phục truyền thống đặc sắc. Phụ nữ dệt vải thổ cẩm. Du khách tham quan, tìm hiểu văn hoá Chăm Islam.",["Mặc trang phục kín đáo","Xem phụ nữ dệt thổ cẩm","Không chụp ảnh trong thánh đường"],"Châu Phong, TX. Tân Châu, An Giang",10.7833,105.2333,"Luôn mở cửa","Miễn phí","Quanh năm",["chăm","islam","làng","văn-hoá"],false,3),
d("rung-tra-su","Rừng tràm Trà Sư","Rừng tràm Trà Sư","an-giang","thien-nhien","Rừng ngập nước tuyệt đẹp với thảm bèo xanh phủ kín mặt nước.","Rừng tràm Trà Sư rộng 845ha, là khu rừng ngập nước tuyệt đẹp nhất ĐBSCL. Mặt nước phủ kín bèo tấm xanh như thảm nhung. Cây tràm cao vút tạo tán rợp bóng. Hàng vạn cò, vạc trú ngụ. Du khách chèo thuyền xuyên rừng, ngắm chim, chụp ảnh. Mùa nước nổi đẹp nhất.",["Chèo thuyền xuyên rừng tràm","Mùa nước nổi (T9–11) đẹp nhất","Mang máy ảnh, cảnh rất đẹp"],"Tịnh Biên, An Giang",10.5833,105.0167,"7:00–17:00","100.000đ (gồm thuyền)","Tháng 9–11",["rừng-tràm","bèo","chim","sông-nước"],false,4),
// HẬU GIANG (3)
d("cho-noi-nga-bay","Chợ nổi Ngã Bảy","Chợ nổi Ngã Bảy (Phụng Hiệp)","hau-giang","van-hoa","Chợ nổi truyền thống tại ngã bảy sông, nét văn hoá sông nước Nam Bộ.","Chợ nổi Ngã Bảy (Phụng Hiệp) họp tại nơi 7 con sông gặp nhau. Ghe xuồng mua bán nông sản, trái cây trên sông. Quy mô nhỏ hơn Cái Răng nhưng nguyên bản hơn. Du khách đi ghe ngắm cảnh, mua hàng trên sông.",["Đi sáng sớm 5–7h","Nhỏ hơn nhưng nguyên bản hơn Cái Răng","Thuê ghe từ bến Phụng Hiệp"],"TX. Ngã Bảy, Hậu Giang",9.8167,105.8167,"5:00–9:00","Thuê ghe: 80.000đ","Sáng sớm",["chợ-nổi","sông","nông-sản","miền-tây"],false,1),
d("khu-du-lich-lung-ngoc-hoang","KDL Lung Ngọc Hoàng","Khu bảo tồn thiên nhiên Lung Ngọc Hoàng","hau-giang","thien-nhien","Rừng tràm và đồng cỏ ngập nước với nhiều loài chim quý.","Khu bảo tồn Lung Ngọc Hoàng rộng 2.800ha, rừng tràm và đồng cỏ ngập nước. Nhiều loài chim nước quý: sếu, cò. Hệ sinh thái đất ngập nước đặc trưng ĐBSCL. Du khách đi thuyền ngắm chim, trekking trên cầu ván xuyên rừng.",["Đi thuyền ngắm chim sáng sớm","Trekking trên cầu ván","Mùa nước nổi đẹp nhất"],"Phụng Hiệp, Hậu Giang",9.7833,105.7333,"7:00–17:00","20.000đ","Tháng 9–12",["rừng-tràm","chim","đất-ngập-nước","sinh-thái"],false,2),
d("vuon-co-vi-thuy","Vườn cò Vị Thuỷ","Vườn cò Vị Thuỷ","hau-giang","thien-nhien","Nơi trú ngụ của hàng vạn con cò giữa vườn cây ăn trái.","Vườn cò Vị Thuỷ ở huyện Vị Thuỷ, nơi hàng vạn con cò trú ngụ trên cây ăn trái. Chiều muộn cò bay về tổ, cảnh tượng ngoạn mục. Nhiều loài cò: cò trắng, cò bợ, cò xanh. Không gian yên bình giữa vườn cây.",["Chiều muộn 16–17h xem cò về","Giữ yên lặng","Mang ống nhòm"],"Vị Thuỷ, Hậu Giang",9.8333,105.8000,"15:00–18:00","10.000đ","Chiều muộn",["cò","chim","vườn","sinh-thái"],false,3),
// SÓC TRĂNG (3)
d("chua-doi-soc-trang","Chùa Dơi","Chùa Dơi (Chùa Mã Tộc)","soc-trang","tam-linh","Ngôi chùa Khmer cổ nổi tiếng với hàng ngàn con dơi trú ngụ trên cây.","Chùa Dơi (Mã Tộc) là chùa Khmer cổ, nổi tiếng với đàn dơi hàng ngàn con trú ngụ trên cây trong khuôn viên. Kiến trúc Khmer lộng lẫy với mái nhọn, tượng thần tinh xảo. Dơi bay đi kiếm ăn lúc hoàng hôn, cảnh tượng ngoạn mục. Chùa là di tích cấp quốc gia.",["Ngắm dơi bay vào hoàng hôn","Không gây ồn ào xua dơi","Tham quan kiến trúc Khmer"],"TP. Sóc Trăng",9.5933,105.9733,"6:00–18:00","Miễn phí","Hoàng hôn",["chùa","khmer","dơi","kiến-trúc"],false,1),
d("chua-kh-leang","Chùa Kh'Leang","Chùa Kh'Leang","soc-trang","tam-linh","Một trong những chùa Khmer cổ nhất và đẹp nhất đồng bằng sông Cửu Long.","Chùa Kh'Leang xây khoảng 500 năm trước, là chùa Khmer cổ nhất Sóc Trăng. Kiến trúc Khmer truyền thống nguyên bản, ít trùng tu. Mái chùa nhiều tầng, hoạ tiết Naga (rắn thần), phù điêu Apsara. Khuôn viên rộng với vườn cây cổ thụ.",["Chiêm ngưỡng kiến trúc Khmer cổ","Kết hợp thăm chùa Dơi","Mặc trang phục kín đáo"],"TP. Sóc Trăng",9.6000,105.9700,"6:00–18:00","Miễn phí","Quanh năm",["chùa","khmer","cổ","kiến-trúc"],false,2),
d("cu-lao-dung","Cù Lao Dung","Cù Lao Dung","soc-trang","thien-nhien","Cù lao phù sa lớn nhất sông Hậu với vườn mía và rừng ngập mặn.","Cù Lao Dung là đảo phù sa lớn nhất cửa sông Hậu, đất đai màu mỡ trồng mía. Du khách đi phà qua sông, đạp xe trên đảo, thăm rừng ngập mặn, vườn mía. Cuộc sống dân đảo bình dị. Mũi cù lao nhìn ra biển. Ít du khách, hoang sơ.",["Đi phà từ Sóc Trăng","Đạp xe quanh cù lao","Thưởng cá lóc nướng trui"],"Cù Lao Dung, Sóc Trăng",9.5000,106.1667,"Luôn mở cửa","Miễn phí","Quanh năm",["cù-lao","mía","rừng-ngập-mặn","hoang-sơ"],false,3),
// BẠC LIÊU (3)
d("nha-cong-tu-bac-lieu","Nhà Công tử Bạc Liêu","Nhà Công tử Bạc Liêu","bac-lieu","lich-su","Biệt thự Pháp cổ của người giàu nhất miền Nam một thuở.","Nhà Công tử Bạc Liêu (Trần Trinh Huy) xây 1919, biệt thự kiến trúc Pháp nguy nga. Công tử Bạc Liêu nổi tiếng với giai thoại đốt tiền nấu trứng, giàu nhất miền Nam. Nay là bảo tàng trưng bày nội thất nguyên bản. Bạc Liêu còn là quê hương bản Dạ cổ hoài lang.",["Tham quan nội thất biệt thự","Nghe giai thoại Công tử Bạc Liêu","Café trong khuôn viên biệt thự"],"TP. Bạc Liêu",9.2900,105.7267,"7:00–17:00","20.000đ","Quanh năm",["biệt-thự","lịch-sử","pháp","giai-thoại"],false,1),
d("quan-am-phat-dai","Quán Âm Phật Đài","Quán Âm Phật Đài","bac-lieu","tam-linh","Tượng Phật Bà Quan Âm cao 11m nhìn ra biển, điểm hành hương nổi tiếng.","Quán Âm Phật Đài nằm ven biển Bạc Liêu, tượng Phật Bà Quan Âm cao 11m trên đài sen nhìn ra biển. Nơi hành hương linh thiêng. Khuôn viên rộng với vườn cây, hồ nước. View biển đẹp, hoàng hôn tuyệt vời.",["Ngắm hoàng hôn tại đây","Viếng tượng Phật Bà","Kết hợp ăn hải sản gần đó"],"Nhà Mát, TP. Bạc Liêu",9.2500,105.6833,"5:00–18:00","Miễn phí","Hoàng hôn",["phật-đài","biển","tâm-linh","hoàng-hôn"],false,2),
d("vuon-chim-bac-lieu","Vườn chim Bạc Liêu","Vườn chim Bạc Liêu","bac-lieu","thien-nhien","Khu trú ngụ hàng chục ngàn con chim giữa rừng ngập mặn ven biển.","Vườn chim Bạc Liêu rộng 130ha, nơi trú ngụ của hàng chục ngàn con chim: cò, vạc, diệc. Rừng ngập mặn ven biển xanh mướt. Chiều muộn chim bay về tổ đông đúc. Có đài quan sát chim. Hệ sinh thái ven biển phong phú.",["Chiều muộn xem chim bay về","Lên đài quan sát","Mang ống nhòm"],"Phước Long, Bạc Liêu",9.2333,105.6667,"6:00–18:00","20.000đ","Chiều muộn",["chim","rừng-ngập-mặn","cò","sinh-thái"],false,3),
// CÀ MAU (3)
d("dat-mui-ca-mau","Đất Mũi Cà Mau","Đất Mũi Cà Mau","ca-mau","thien-nhien","Điểm cực Nam Tổ quốc – nơi đất nước bắt đầu lấn ra biển.","Đất Mũi Cà Mau là điểm cực Nam của Việt Nam, nơi giao nhau của biển Đông và biển Tây. Mốc toạ độ GPS đánh dấu vị trí cực Nam. Đất bồi lấn ra biển hàng năm. Rừng đước ngập mặn bao phủ. Biểu tượng thuyền buồm và mốc GPS là điểm check-in quan trọng.",["Chụp ảnh tại mốc toạ độ cực Nam","Đi xuồng qua rừng đước","Ăn cua biển Cà Mau"],"Đất Mũi, Ngọc Hiển, Cà Mau",8.6167,104.7333,"Luôn mở cửa","20.000đ","Tháng 11–4",["cực-nam","đất-mũi","rừng-đước","biểu-tượng"],false,1),
d("vuon-quoc-gia-u-minh-ha","VQG U Minh Hạ","Vườn Quốc gia U Minh Hạ","ca-mau","thien-nhien","Rừng tràm ngập nước bao la – hệ sinh thái đất ngập nước lớn nhất VN.","VQG U Minh Hạ rộng 8.286ha, rừng tràm ngập nước bao la. Hệ sinh thái đất ngập nước quan trọng nhất ĐBSCL. Nhiều loài cá, rùa, rắn, chim. Du khách đi xuồng xuyên rừng tràm. Mùa khô câu cá đồng, mùa nước bắt cá, ong rừng.",["Đi xuồng xuyên rừng tràm","Thử mật ong U Minh","Mùa khô câu cá đồng"],"U Minh, Cà Mau",9.1333,104.9667,"7:00–17:00","30.000đ","Tháng 12–4",["rừng-tràm","đất-ngập-nước","mật-ong","xuồng"],false,2),
d("hon-da-bac","Hòn Đá Bạc","Hòn Đá Bạc","ca-mau","thien-nhien","Cụm đảo nhỏ ngoài khơi với đá trắng bạc và truyền thuyết nàng tiên.","Hòn Đá Bạc là cụm đảo đá nhỏ ngoài khơi Cà Mau, đá có ánh trắng bạc khi phản chiếu nắng. Gắn truyền thuyết nàng tiên xuống tắm. Trên đảo có đền thờ, cây cổ thụ. Phong cảnh biển hoang sơ. Đi ca nô từ Khánh Hội mất 30 phút.",["Đi ca nô từ bến Khánh Hội","Tham quan khoảng 1 giờ","Mang theo đồ ăn nhẹ"],"Khánh Bình Tây, Trần Văn Thời, Cà Mau",9.0167,104.7333,"7:00–16:00","Ca nô: 100.000đ","Tháng 11–4",["đảo","đá-bạc","biển","truyền-thuyết"],false,3),
];

const op=path.join(__dirname,'../src/data/destinations-nam.json');
fs.writeFileSync(op,JSON.stringify(dests,null,2),'utf-8');
console.log(`Generated ${dests.length} Miền Nam destinations`);
